/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents an additional recipient (other than the merchant) receiving a portion of this tender. */

public struct AdditionalRecipient: Codable {

    /** The location ID for a recipient (other than the merchant) receiving a portion of this tender. */
    public let locationId: String
    /** The description of the additional recipient. */
    public let _description: String
    /** The amount of money distributed to the recipient. */
    public let amountMoney: Money
    /** The unique ID for this [AdditionalRecipientReceivable](#type-additionalrecipientreceivable), assigned by the server. */
    public let receivableId: String?

    public init(locationId: String, _description: String, amountMoney: Money, receivableId: String?) {
        self.locationId = locationId
        self._description = _description
        self.amountMoney = amountMoney
        self.receivableId = receivableId
    }

    public enum CodingKeys: String, CodingKey { 
        case locationId = "location_id"
        case _description = "description"
        case amountMoney = "amount_money"
        case receivableId = "receivable_id"
    }

}

