/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Reflects the current status of a balance payment. */

public struct BalancePaymentDetails: Codable {

    /** ID for the account used to fund the payment. */
    public let accountId: String?
    /** The balance payment’s current state. Can be &#x60;COMPLETED&#x60; or &#x60;FAILED&#x60;. */
    public let status: String?

    public init(accountId: String?, status: String?) {
        self.accountId = accountId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case accountId = "account_id"
        case status
    }

}

