/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct BatchChangeInventoryRequest: Codable {

    /** A client-supplied, universally unique identifier (UUID) for the request.  See [Idempotency](/basics/api101/idempotency) in the [API Development 101](/basics/api101/overview) section for more information. */
    public let idempotencyKey: String?
    /** The set of physical counts and inventory adjustments to be made. Changes are applied based on the client-supplied timestamp and may be sent out of order. Max size is 100 changes. */
    public let changes: [InventoryChange]?
    /** Indicates whether the current physical count should be ignored if the quantity is unchanged since the last physical count. Default: &#x60;true&#x60;. */
    public let ignoreUnchangedCounts: Bool?

    public init(idempotencyKey: String?, changes: [InventoryChange]?, ignoreUnchangedCounts: Bool?) {
        self.idempotencyKey = idempotencyKey
        self.changes = changes
        self.ignoreUnchangedCounts = ignoreUnchangedCounts
    }

    public enum CodingKeys: String, CodingKey { 
        case idempotencyKey = "idempotency_key"
        case changes
        case ignoreUnchangedCounts = "ignore_unchanged_counts"
    }

}

