/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct BatchRetrieveCatalogObjectsRequest: Codable {

    /** The IDs of the [CatalogObject](#type-catalogobject)s to be retrieved. */
    public let objectIds: [String]
    /** If &#x60;true&#x60;, the response will include additional objects that are related to the requested objects, as follows:  If the &#x60;objects&#x60; field of the response contains a [CatalogItem](#type-catalogitem),  its associated [CatalogCategory](#type-catalogcategory), [CatalogTax](#type-catalogtax)es, [CatalogImage](#type-catalogimage)s and [CatalogModifierList](#type-catalogmodifierlist)s will be returned in the &#x60;related_objects&#x60; field of the response. If the &#x60;objects&#x60; field of the response contains a [CatalogItemVariation](#type-catalogitemvariation), its parent [CatalogItem](#type-catalogitem) will be returned in the &#x60;related_objects&#x60; field of the response. */
    public let includeRelatedObjects: Bool?

    public init(objectIds: [String], includeRelatedObjects: Bool?) {
        self.objectIds = objectIds
        self.includeRelatedObjects = includeRelatedObjects
    }

    public enum CodingKeys: String, CodingKey { 
        case objectIds = "object_ids"
        case includeRelatedObjects = "include_related_objects"
    }

}

