/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in requests to the BatchRetrieveOrders endpoint. */

public struct BatchRetrieveOrdersRequest: Codable {

    /** The IDs of the orders to retrieve. A maximum of 100 orders can be retrieved per request. */
    public let orderIds: [String]

    public init(orderIds: [String]) {
        self.orderIds = orderIds
    }

    public enum CodingKeys: String, CodingKey { 
        case orderIds = "order_ids"
    }

}

