/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A record of an employee&#39;s break during a shift. */

public struct Break: Codable, Identifiable {

    /** UUID for this object */
    public let id: String?
    /** RFC 3339; follows same timezone info as &#x60;Shift&#x60;. Precision up to the minute is respected; seconds are truncated. */
    public let startAt: String
    /** RFC 3339; follows same timezone info as &#x60;Shift&#x60;. Precision up to the minute is respected; seconds are truncated. The &#x60;end_at&#x60; minute is not counted when the break length is calculated. For example, a break from &#x60;00:00&#x60; to &#x60;00:11&#x60;  is considered a 10 minute break (midnight to 10 minutes after midnight). */
    public let endAt: String?
    /** The &#x60;BreakType&#x60; this &#x60;Break&#x60; was templated on. */
    public let breakTypeId: String
    /** A human-readable name. */
    public let name: String
    /** Format: RFC-3339 P[n]Y[n]M[n]DT[n]H[n]M[n]S. The expected length of the break. */
    public let expectedDuration: String
    /** Whether this break counts towards time worked for compensation purposes. */
    public let isPaid: Bool

    public init(id: String?, startAt: String, endAt: String?, breakTypeId: String, name: String, expectedDuration: String, isPaid: Bool) {
        self.id = id
        self.startAt = startAt
        self.endAt = endAt
        self.breakTypeId = breakTypeId
        self.name = name
        self.expectedDuration = expectedDuration
        self.isPaid = isPaid
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case startAt = "start_at"
        case endAt = "end_at"
        case breakTypeId = "break_type_id"
        case name
        case expectedDuration = "expected_duration"
        case isPaid = "is_paid"
    }

}

