/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  Represents a period of time during which a business location is open. */

public struct BusinessHoursPeriod: Codable {

    /** The day of week for this time period. See [DayOfWeek](#type-dayofweek) for possible values */
    public let dayOfWeek: DayOfWeek?
    /** The start time of a business hours period, specified in local time using partial-time RFC3339 format. */
    public let startLocalTime: String?
    /** The end time of a business hours period, specified in local time using partial-time RFC3339 format. */
    public let endLocalTime: String?

    public init(dayOfWeek: DayOfWeek?, startLocalTime: String?, endLocalTime: String?) {
        self.dayOfWeek = dayOfWeek
        self.startLocalTime = startLocalTime
        self.endLocalTime = endLocalTime
    }

    public enum CodingKeys: String, CodingKey { 
        case dayOfWeek = "day_of_week"
        case startLocalTime = "start_local_time"
        case endLocalTime = "end_local_time"
    }

}

