/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Return value from the [CancelPaymentByIdempotencyKey](#endpoint-payments-cancelpaymentbyidempotencykey) endpoint.  On success, &#x60;errors&#x60; will be empty. */

public struct CancelPaymentByIdempotencyKeyResponse: Codable {

    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(errors: [ModelError]?) {
        self.errors = errors
    }

}

