/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates a card&#39;s brand, such as &#x60;VISA&#x60; or &#x60;MASTERCARD&#x60;. */
public enum CardBrand: String, Codable {
    case otherBrand = "OTHER_BRAND"
    case visa = "VISA"
    case mastercard = "MASTERCARD"
    case americanExpress = "AMERICAN_EXPRESS"
    case discover = "DISCOVER"
    case discoverDiners = "DISCOVER_DINERS"
    case jcb = "JCB"
    case chinaUnionpay = "CHINA_UNIONPAY"
    case squareGiftCard = "SQUARE_GIFT_CARD"

}
