/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents the payment details of a card to be used for payments. These details are determined by the &#x60;card_nonce&#x60; generated by &#x60;SqPaymentForm&#x60;. */

public struct Card: Codable, Identifiable {

    /** Unique ID for this card. Generated by Square. */
    public let id: String?
    /** The card&#39;s brand (such as &#x60;VISA&#x60;). See [CardBrand](#type-cardbrand) for possible values */
    public let cardBrand: CardBrand?
    /** The last 4 digits of the card number. */
    public let last4: String?
    /** The expiration month of the associated card as an integer between 1 and 12. */
    public let expMonth: Int64?
    /** The four-digit year of the card&#39;s expiration date. */
    public let expYear: Int64?
    /** The name of the cardholder. */
    public let cardholderName: String?
    /** The billing address for this card. */
    public let billingAddress: Address?
    /** A unique, Square-assigned ID that identifies the card across multiple locations and applications for a single Square account. */
    public let fingerprint: String?

    public init(id: String?, cardBrand: CardBrand?, last4: String?, expMonth: Int64?, expYear: Int64?, cardholderName: String?, billingAddress: Address?, fingerprint: String?) {
        self.id = id
        self.cardBrand = cardBrand
        self.last4 = last4
        self.expMonth = expMonth
        self.expYear = expYear
        self.cardholderName = cardholderName
        self.billingAddress = billingAddress
        self.fingerprint = fingerprint
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case cardBrand = "card_brand"
        case last4 = "last_4"
        case expMonth = "exp_month"
        case expYear = "exp_year"
        case cardholderName = "cardholder_name"
        case billingAddress = "billing_address"
        case fingerprint
    }

}

