/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A tax in the Catalog object model. */

public struct CatalogTax: Codable {

    /** The tax&#39;s name. Searchable. This field has max length of 255 Unicode code points. */
    public let name: String?
    /** Whether the tax is calculated based on a payment&#39;s subtotal or total. See [TaxCalculationPhase](#type-taxcalculationphase) for possible values */
    public let calculationPhase: TaxCalculationPhase?
    /** Whether the tax is &#x60;ADDITIVE&#x60; or &#x60;INCLUSIVE&#x60;. See [TaxInclusionType](#type-taxinclusiontype) for possible values */
    public let inclusionType: TaxInclusionType?
    /** The percentage of the tax in decimal form, using a &#x60;&#39;.&#39;&#x60; as the decimal separator and without a &#x60;&#39;%&#39;&#x60; sign. A value of &#x60;7.5&#x60; corresponds to 7.5%. */
    public let percentage: String?
    /** If &#x60;true&#x60;, the fee applies to custom amounts entered into the Square Point of Sale app that are not associated with a particular [CatalogItem](#type-catalogitem). */
    public let appliesToCustomAmounts: Bool?
    /** If &#x60;true&#x60;, the tax will be shown as enabled in the Square Point of Sale app. */
    public let enabled: Bool?

    public init(name: String?, calculationPhase: TaxCalculationPhase?, inclusionType: TaxInclusionType?, percentage: String?, appliesToCustomAmounts: Bool?, enabled: Bool?) {
        self.name = name
        self.calculationPhase = calculationPhase
        self.inclusionType = inclusionType
        self.percentage = percentage
        self.appliesToCustomAmounts = appliesToCustomAmounts
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case calculationPhase = "calculation_phase"
        case inclusionType = "inclusion_type"
        case percentage
        case appliesToCustomAmounts = "applies_to_custom_amounts"
        case enabled
    }

}

