/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents the unit used to measure a [CatalogItemVariation](#type-catalogitemvariation) and specifies the precision for decimal quantities. */

public struct CatalogMeasurementUnit: Codable {

    /** Indicates the unit used to measure the quantity of a catalog item variation. */
    public let measurementUnit: MeasurementUnit?
    /**  Represents the maximum number of positions allowed after the decimal in quantities measured with this unit. For example, if the precision is 2, then an itemization’s quantity can be 0.01, 0.12, etc.  Min: 0  Max: 5  Default: 3 */
    public let precision: Int?

    public init(measurementUnit: MeasurementUnit?, precision: Int?) {
        self.measurementUnit = measurementUnit
        self.precision = precision
    }

    public enum CodingKeys: String, CodingKey { 
        case measurementUnit = "measurement_unit"
        case precision
    }

}

