/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  A list of item option values that can be assigned to item variations. For example, a t-shirt item may offer a color option or a size option. */

public struct CatalogItemOptionForItem: Codable {

    /** The unique id of the item option, used to form the dimensions of the item option matrix in a specified order. */
    public let itemOptionId: String?

    public init(itemOptionId: String?) {
        self.itemOptionId = itemOptionId
    }

    public enum CodingKeys: String, CodingKey { 
        case itemOptionId = "item_option_id"
    }

}

