/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** An enumerated value that can link a [CatalogItemVariation(#type-catalogitemvariation) to an item option as one of its item option values. */

public struct CatalogItemOptionValue: Codable {

    /** Unique ID of the associated item option. */
    public let itemOptionId: String?
    /** Name of this item option value. Searchable. */
    public let name: String?
    /** The option value&#39;s human-readable description. */
    public let _description: String?
    /** The HTML color for this value in the format #FFRRGGBB or #RRGGBB (e.g., \&quot;#ff8d4e85\&quot;). Only displayed if parent Item Option&#39;s &#x60;show_colors&#x60; flag is enabled. value. */
    public let color: String?
    /** Determines where this option value appears in a list of option values. */
    public let ordinal: Int?
    /** The number of [CatalogItemVariation(#type-catalogitemvariation)s that currently make use of this Item Option value. Present only if &#x60;retrieve_counts&#x60; was specified on the request used to retrieve the parent Item Option of this value.  Maximum: 100 counts. */
    public let itemVariationCount: Int64?

    public init(itemOptionId: String?, name: String?, _description: String?, color: String?, ordinal: Int?, itemVariationCount: Int64?) {
        self.itemOptionId = itemOptionId
        self.name = name
        self._description = _description
        self.color = color
        self.ordinal = ordinal
        self.itemVariationCount = itemVariationCount
    }

    public enum CodingKeys: String, CodingKey { 
        case itemOptionId = "item_option_id"
        case name
        case _description = "description"
        case color
        case ordinal
        case itemVariationCount = "item_variation_count"
    }

}

