/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct CatalogQueryExact: Codable {

    /** The name of the attribute to be searched. */
    public let attributeName: String
    /** The desired value of the search attribute. */
    public let attributeValue: String

    public init(attributeName: String, attributeValue: String) {
        self.attributeName = attributeName
        self.attributeValue = attributeValue
    }

    public enum CodingKeys: String, CodingKey { 
        case attributeName = "attribute_name"
        case attributeValue = "attribute_value"
    }

}

