/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A discount in the Catalog object model. */

public struct CatalogDiscount: Codable {

    /** The discount&#39;s name. Searchable. This field has max length of 255 Unicode code points. */
    public let name: String?
    /** Indicates whether the discount is a fixed amount or percentage, or entered at the time of sale. See [CatalogDiscountType](#type-catalogdiscounttype) for possible values */
    public let discountType: CatalogDiscountType?
    /** The percentage of the discount as a string representation of a decimal number, using a &#x60;.&#x60; as the decimal separator and without a &#x60;%&#x60; sign. A value of &#x60;7.5&#x60; corresponds to &#x60;7.5%&#x60;. Specify a percentage of &#x60;0&#x60; if &#x60;discount_type&#x60; is &#x60;VARIABLE_PERCENTAGE&#x60;.  Do not include this field for amount-based or variable discounts. */
    public let percentage: String?
    /** The amount of the discount. Specify an amount of &#x60;0&#x60; if &#x60;discount_type&#x60; is &#x60;VARIABLE_AMOUNT&#x60;.  Do not include this field for percentage-based or variable discounts. */
    public let amountMoney: Money?
    /** Indicates whether a mobile staff member needs to enter their PIN to apply the discount to a payment in the Square Point of Sale app. */
    public let pinRequired: Bool?
    /** The color of the discount&#39;s display label in the Square Point of Sale app. This must be a valid hex color code. */
    public let labelColor: String?

    public init(name: String?, discountType: CatalogDiscountType?, percentage: String?, amountMoney: Money?, pinRequired: Bool?, labelColor: String?) {
        self.name = name
        self.discountType = discountType
        self.percentage = percentage
        self.amountMoney = amountMoney
        self.pinRequired = pinRequired
        self.labelColor = labelColor
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case discountType = "discount_type"
        case percentage
        case amountMoney = "amount_money"
        case pinRequired = "pin_required"
        case labelColor = "label_color"
    }

}

