/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct CatalogQueryText: Codable {

    /** A list of one, two, or three search keywords. Keywords with fewer than three characters are ignored. */
    public let keywords: [String]

    public init(keywords: [String]) {
        self.keywords = keywords
    }

}

