/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct CatalogModifierOverride: Codable {

    /** The ID of the [CatalogModifier](#type-catalogmodifier) whose default behavior is being overridden. */
    public let modifierId: String
    /** If &#x60;true&#x60;, this [CatalogModifier](#type-catalogmodifier) should be selected by default for this [CatalogItem](#type-catalogitem). */
    public let onByDefault: Bool?

    public init(modifierId: String, onByDefault: Bool?) {
        self.modifierId = modifierId
        self.onByDefault = onByDefault
    }

    public enum CodingKeys: String, CodingKey { 
        case modifierId = "modifier_id"
        case onByDefault = "on_by_default"
    }

}

