/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */

import Foundation

/** A category to which an [CatalogItem](#type-catalogitem) belongs in the Catalog object model. */

public struct CatalogCategory: Codable {

    /** The category&#39;s name. Searchable. This field has max length of 255 Unicode code points. */
    public let name: String?

    public init(name: String?) {
        self.name = name
    }

}

