/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  The type of a [CatalogItem](#type-catalogitem). Connect V2 only allows the creation of &#x60;REGULAR&#x60; or &#x60;APPOINTMENTS_SERVICE&#x60; items. */
public enum CatalogItemProductType: String, Codable {
    case regular = "REGULAR"
    case giftCard = "GIFT_CARD"
    case appointmentsService = "APPOINTMENTS_SERVICE"
    case retailItem = "RETAIL_ITEM"
    case restaurantItem = "RESTAURANT_ITEM"

}
