/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct CatalogQueryPrefix: Codable {

    /** The name of the attribute to be searched. */
    public let attributeName: String
    /** The desired prefix of the search attribute value. */
    public let attributePrefix: String

    public init(attributeName: String, attributePrefix: String) {
        self.attributeName = attributeName
        self.attributePrefix = attributePrefix
    }

    public enum CodingKeys: String, CodingKey { 
        case attributeName = "attribute_name"
        case attributePrefix = "attribute_prefix"
    }

}

