/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A mapping between a client-supplied temporary ID and a permanent server ID. */

public struct CatalogIdMapping: Codable {

    /** The client-supplied, temporary &#x60;#&#x60;-prefixed ID for a new [CatalogObject](#type-catalogobject). */
    public let clientObjectId: String?
    /** The permanent ID for the [CatalogObject](#type-catalogobject) created by the server. */
    public let objectId: String?

    public init(clientObjectId: String?, objectId: String?) {
        self.clientObjectId = clientObjectId
        self.objectId = objectId
    }

    public enum CodingKeys: String, CodingKey { 
        case clientObjectId = "client_object_id"
        case objectId = "object_id"
    }

}

