/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct CatalogQueryItemsForTax: Codable {

    /** A set of [CatalogTax](#type-catalogtax) IDs to be used to find associated [CatalogItem](#type-catalogitem)s. */
    public let taxIds: [String]

    public init(taxIds: [String]) {
        self.taxIds = taxIds
    }

    public enum CodingKeys: String, CodingKey { 
        case taxIds = "tax_ids"
    }

}

