/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** How to apply a [CatalogDiscount](#type-catalogdiscount) to a [CatalogItem](#type-catalogitem). */
public enum CatalogDiscountType: String, Codable {
    case fixedPercentage = "FIXED_PERCENTAGE"
    case fixedAmount = "FIXED_AMOUNT"
    case variablePercentage = "VARIABLE_PERCENTAGE"
    case variableAmount = "VARIABLE_AMOUNT"

}
