/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Controls the properties of a [CatalogModifierList](#type-catalogmodifierlist) as it applies to this [CatalogItem](#type-catalogitem). */

public struct CatalogItemModifierListInfo: Codable {

    /** The ID of the [CatalogModifierList](#type-catalogmodifierlist) controlled by this [CatalogModifierListInfo](#type-catalogmodifierlistinfo). */
    public let modifierListId: String
    /** A set of [CatalogModifierOverride](#type-catalogmodifieroverride) objects that override whether a given [CatalogModifier](#type-catalogmodifier) is enabled by default. */
    public let modifierOverrides: [CatalogModifierOverride]?
    /** If zero or larger, the smallest number of [CatalogModifier](#type-catalogmodifier)s that must be selected from this [CatalogModifierList](#type-catalogmodifierlist). */
    public let minSelectedModifiers: Int?
    /** If zero or larger, the largest number of [CatalogModifier](#type-catalogmodifier)s that can be selected from this [CatalogModifierList](#type-catalogmodifierlist). */
    public let maxSelectedModifiers: Int?
    /** If &#x60;true&#x60;, enable this [CatalogModifierList](#type-catalogmodifierlist). */
    public let enabled: Bool?

    public init(modifierListId: String, modifierOverrides: [CatalogModifierOverride]?, minSelectedModifiers: Int?, maxSelectedModifiers: Int?, enabled: Bool?) {
        self.modifierListId = modifierListId
        self.modifierOverrides = modifierOverrides
        self.minSelectedModifiers = minSelectedModifiers
        self.maxSelectedModifiers = maxSelectedModifiers
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey { 
        case modifierListId = "modifier_list_id"
        case modifierOverrides = "modifier_overrides"
        case minSelectedModifiers = "min_selected_modifiers"
        case maxSelectedModifiers = "max_selected_modifiers"
        case enabled
    }

}

