/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A group of variations for a [CatalogItem](#type-catalogitem)&#39;s. */

public struct CatalogItemOption: Codable {

    /** The item option&#39;s display name for the seller. Must be unique across all item options. Searchable. */
    public let name: String?
    /** The item option&#39;s display name for the customer. Searchable. */
    public let displayName: String?
    /** The item option&#39;s human-readable description. Displays for in the Square Point of Sale app for the seller and in the Online Store or on receipts for the buyer. */
    public let _description: String?
    /** If true, display colors for entries in &#x60;values&#x60; when present. */
    public let showColors: Bool?
    /** A list of [CatalogObject](#type-catalogobject)s containing the [CatalogItemOptionValue](#type-catalogitemoptionvalue)s for this item. */
    public let values: [CatalogObject]?
    /** The number of [CatalogItem](#type-catalogitem)s currently associated with this item option. Present only if the &#x60;include_counts&#x60; was specified in the request. Any count over 100 will be returned as &#x60;100&#x60;. */
    public let itemCount: Int64?

    public init(name: String?, displayName: String?, _description: String?, showColors: Bool?, values: [CatalogObject]?, itemCount: Int64?) {
        self.name = name
        self.displayName = displayName
        self._description = _description
        self.showColors = showColors
        self.values = values
        self.itemCount = itemCount
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case displayName = "display_name"
        case _description = "description"
        case showColors = "show_colors"
        case values
        case itemCount = "item_count"
    }

}

