/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Square Checkout lets merchants accept online payments for supported payment types using a checkout workflow hosted on squareup.com. */

public struct Checkout: Codable, Identifiable {

    /** ID generated by Square Checkout when a new checkout is requested. */
    public let id: String?
    /** The URL that the buyer&#39;s browser should be redirected to after the checkout is completed. */
    public let checkoutPageUrl: String?
    /** If &#x60;true&#x60;, Square Checkout will collect shipping information on your behalf and store that information with the transaction information in your Square Dashboard.  Default: &#x60;false&#x60;. */
    public let askForShippingAddress: Bool?
    /** The email address to display on the Square Checkout confirmation page and confirmation email that the buyer can use to contact the merchant.  If this value is not set, the confirmation page and email will display the primary email address associated with the merchant&#39;s Square account.  Default: none; only exists if explicitly set. */
    public let merchantSupportEmail: String?
    /** If provided, the buyer&#39;s email is pre-populated on the checkout page as an editable text field.  Default: none; only exists if explicitly set. */
    public let prePopulateBuyerEmail: String?
    /** If provided, the buyer&#39;s shipping info is pre-populated on the checkout page as editable text fields.  Default: none; only exists if explicitly set. */
    public let prePopulateShippingAddress: Address?
    /** The URL to redirect to after checkout is completed with &#x60;checkoutId&#x60;, Square&#39;s &#x60;orderId&#x60;, &#x60;transactionId&#x60;, and &#x60;referenceId&#x60; appended as URL parameters. For example, if the provided redirect_url is &#x60;http://www.example.com/order-complete&#x60;, a successful transaction redirects the customer to:  &#x60;http://www.example.com/order-complete?checkoutId&#x3D;xxxxxx&amp;orderId&#x3D;xxxxxx&amp;referenceId&#x3D;xxxxxx&amp;transactionId&#x3D;xxxxxx&#x60;  If you do not provide a redirect URL, Square Checkout will display an order confirmation page on your behalf; however Square strongly recommends that you provide a redirect URL so you can verify the transaction results and finalize the order through your existing/normal confirmation workflow. */
    public let redirectUrl: String?
    /** Order to be checked out. */
    public let order: Order?
    /** The time when the checkout was created, in RFC 3339 format. */
    public let createdAt: String?
    /** Additional recipients (other than the merchant) receiving a portion of this checkout. For example, fees assessed on the purchase by a third party integration. */
    public let additionalRecipients: [AdditionalRecipient]?

    public init(id: String?, checkoutPageUrl: String?, askForShippingAddress: Bool?, merchantSupportEmail: String?, prePopulateBuyerEmail: String?, prePopulateShippingAddress: Address?, redirectUrl: String?, order: Order?, createdAt: String?, additionalRecipients: [AdditionalRecipient]?) {
        self.id = id
        self.checkoutPageUrl = checkoutPageUrl
        self.askForShippingAddress = askForShippingAddress
        self.merchantSupportEmail = merchantSupportEmail
        self.prePopulateBuyerEmail = prePopulateBuyerEmail
        self.prePopulateShippingAddress = prePopulateShippingAddress
        self.redirectUrl = redirectUrl
        self.order = order
        self.createdAt = createdAt
        self.additionalRecipients = additionalRecipients
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case checkoutPageUrl = "checkout_page_url"
        case askForShippingAddress = "ask_for_shipping_address"
        case merchantSupportEmail = "merchant_support_email"
        case prePopulateBuyerEmail = "pre_populate_buyer_email"
        case prePopulateShippingAddress = "pre_populate_shipping_address"
        case redirectUrl = "redirect_url"
        case order
        case createdAt = "created_at"
        case additionalRecipients = "additional_recipients"
    }

}

