/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Completes a payment.  By default, payments are set to autocomplete immediately after they are created. To complete payments manually, set &#x60;autocomplete&#x60; to false. */

public struct CompletePaymentRequest: Codable {



}

