/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the response body of a request to the CreateCheckout endpoint. */

public struct CreateCheckoutResponse: Codable {

    /** The newly created checkout. If the same request was made with the same idempotency_key, this will be the checkout created with the idempotency_key. */
    public let checkout: Checkout?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(checkout: Checkout?, errors: [ModelError]?) {
        self.checkout = checkout
        self.errors = errors
    }

}

