/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The response to the request to create a &#x60;BreakType&#x60;. Contains the created &#x60;BreakType&#x60; object. May contain a set of &#x60;Error&#x60; objects if the request resulted in errors. */

public struct CreateBreakTypeResponse: Codable {

    /** The &#x60;BreakType&#x60; that was created by the request. */
    public let breakType: BreakType?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(breakType: BreakType?, errors: [ModelError]?) {
        self.breakType = breakType
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case breakType = "break_type"
        case errors
    }

}

