/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** __Deprecated__: Please use the [OrderLineItemDiscount](#type-orderlineitemdiscount) type in the order field of [CreateOrderRequest](#type-createorderrequest) instead.  Represents a discount that can apply to either a single line item or an entire order. */

public struct CreateOrderRequestDiscount: Codable {

    /** Only used for catalog discounts. The catalog object ID for an existing [CatalogDiscount](#type-catalogdiscount).  Do not provide a value for this field if you provide values in other fields for an ad hoc discount. */
    public let catalogObjectId: String?
    /** Only used for ad hoc discounts. The discount&#39;s name. */
    public let name: String?
    /** Only used for ad hoc discounts. The percentage of the discount, as a string representation of a decimal number.  A value of &#x60;7.25&#x60; corresponds to a percentage of 7.25%. This value range between 0.0 up to 100.0 */
    public let percentage: String?
    /** Only used for ad hoc discounts. The monetary amount of the discount. */
    public let amountMoney: Money?

    public init(catalogObjectId: String?, name: String?, percentage: String?, amountMoney: Money?) {
        self.catalogObjectId = catalogObjectId
        self.name = name
        self.percentage = percentage
        self.amountMoney = amountMoney
    }

    public enum CodingKeys: String, CodingKey { 
        case catalogObjectId = "catalog_object_id"
        case name
        case percentage
        case amountMoney = "amount_money"
    }

}

