/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the request body of a request to the CreateCustomerCard endpoint. */

public struct CreateCustomerCardRequest: Codable {

    /** A card nonce representing the credit card to link to the customer.  Card nonces are generated by the &#x60;SqPaymentForm&#x60; that buyers enter their card information into. See [Embedding the payment form](/payment-form/payment-form-walkthrough) for more information.  __Note:__ Card nonces generated by digital wallets (e.g., Apple Pay) cannot be used to create a customer card. */
    public let cardNonce: String
    /** Address information for the card on file. Only the &#x60;postal_code&#x60; field is required for payments in the US and Canada. */
    public let billingAddress: Address?
    /** The full name printed on the credit card. */
    public let cardholderName: String?
    /** An identifying token generated by &#x60;SqPaymentForm.verifyBuyer()&#x60;. Verification tokens encapsulate customer device information and 3-D Secure challenge results to indicate that Square has verified the buyer identity. */
    public let verificationToken: String?

    public init(cardNonce: String, billingAddress: Address?, cardholderName: String?, verificationToken: String?) {
        self.cardNonce = cardNonce
        self.billingAddress = billingAddress
        self.cardholderName = cardholderName
        self.verificationToken = verificationToken
    }

    public enum CodingKeys: String, CodingKey { 
        case cardNonce = "card_nonce"
        case billingAddress = "billing_address"
        case cardholderName = "cardholder_name"
        case verificationToken = "verification_token"
    }

}

