/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A request to create a new &#x60;BreakType&#x60; */

public struct CreateBreakTypeRequest: Codable {

    /** Unique string value to insure idempotency of the operation */
    public let idempotencyKey: String?
    /** The &#x60;BreakType&#x60; to be created. */
    public let breakType: BreakType

    public init(idempotencyKey: String?, breakType: BreakType) {
        self.idempotencyKey = idempotencyKey
        self.breakType = breakType
    }

    public enum CodingKeys: String, CodingKey { 
        case idempotencyKey = "idempotency_key"
        case breakType = "break_type"
    }

}

