/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates whether customers should be included in, or excluded from, the result set when they match the filtering criteria. */
public enum CustomerInclusionExclusion: String, Codable {
    case include = "INCLUDE"
    case exclude = "EXCLUDE"

}
