/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates the field to use for sorting customer profiles. For example, by total money spent with the merchant or the date of their first purchase. */

public struct CustomerSort: Codable {

    /** The field to sort the results on. It could be the total money spent at the merchant, the date of the first visit (etc). See [CustomerSortField](#type-customersortfield) for possible values */
    public let field: CustomerSortField?
    /** Indicates the order in which results should be displayed based on the value of the sort field. String comparisons use standard alphabetic comparison to determine order. Strings representing numbers are sorted as strings. See [SortOrder](#type-sortorder) for possible values */
    public let order: SortOrder?

    public init(field: CustomerSortField?, order: SortOrder?) {
        self.field = field
        self.order = order
    }

}

