/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates the method used to create the customer profile. */
public enum CustomerCreationSource: String, Codable {
    case other = "OTHER"
    case appointments = "APPOINTMENTS"
    case coupon = "COUPON"
    case deletionRecovery = "DELETION_RECOVERY"
    case directory = "DIRECTORY"
    case egifting = "EGIFTING"
    case emailCollection = "EMAIL_COLLECTION"
    case feedback = "FEEDBACK"
    case _import = "IMPORT"
    case invoices = "INVOICES"
    case loyalty = "LOYALTY"
    case marketing = "MARKETING"
    case merge = "MERGE"
    case onlineStore = "ONLINE_STORE"
    case instantProfile = "INSTANT_PROFILE"
    case terminal = "TERMINAL"
    case thirdParty = "THIRD_PARTY"
    case thirdPartyImport = "THIRD_PARTY_IMPORT"
    case unmergeRecovery = "UNMERGE_RECOVERY"

}
