/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Creation source filter.  If one or more creation sources are set, customer profiles are included in, or excluded from, the result if they match at least one of the filter criteria. */

public struct CustomerCreationSourceFilter: Codable {

    /** The list of creation sources used as filtering criteria. See [CustomerCreationSource](#type-customercreationsource) for possible values */
    public let values: [CustomerCreationSource]?
    /** Indicates whether a customer profile matching the filter criteria should be included in the result or excluded from the result. Default: &#x60;INCLUDE&#x60;. See [CustomerInclusionExclusion](#type-customerinclusionexclusion) for possible values */
    public let rule: CustomerInclusionExclusion?

    public init(values: [CustomerCreationSource]?, rule: CustomerInclusionExclusion?) {
        self.values = values
        self.rule = rule
    }

}

