/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents a query (filtering and sorting criteria) used to search for customer profiles. */

public struct CustomerQuery: Codable {

    /** A list of filter criteria. */
    public let filter: CustomerFilter?
    /** Sort criteria for query results. The default sort behavior is to order customers alphabetically by &#x60;given_name&#x60; and &#x60;last_name&#x60;. */
    public let sort: CustomerSort?

    public init(filter: CustomerFilter?, sort: CustomerSort?) {
        self.filter = filter
        self.sort = sort
    }

}

