/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A range defined by two dates. Used for filtering a query for Connect v2  objects that have date properties. */

public struct DateRange: Codable {

    /** String in &#x60;YYYY-MM-DD&#x60; format, e.g. &#x60;2017-10-31&#x60; per the ISO 8601 extended format for calendar dates. The beginning of a date range (inclusive) */
    public let startDate: String?
    /** String in &#x60;YYYY-MM-DD&#x60; format, e.g. &#x60;2017-10-31&#x60; per the ISO 8601 extended format for calendar dates. The end of a date range (inclusive) */
    public let endDate: String?

    public init(startDate: String?, endDate: String?) {
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey { 
        case startDate = "start_date"
        case endDate = "end_date"
    }

}

