/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The hourly wage rate that an employee will earn on a &#x60;Shift&#x60; for doing the job specified by the &#x60;title&#x60; property of this object. */

public struct EmployeeWage: Codable, Identifiable {

    /** UUID for this object. */
    public let id: String?
    /** The &#x60;Employee&#x60; that this wage is assigned to. */
    public let employeeId: String
    /** The job title that this wage relates to. */
    public let title: String?
    /** Can be a custom-set hourly wage or the calculated effective hourly wage based on annual wage and hours worked per week. */
    public let hourlyRate: Money?

    public init(id: String?, employeeId: String, title: String?, hourlyRate: Money?) {
        self.id = id
        self.employeeId = employeeId
        self.title = title
        self.hourlyRate = hourlyRate
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case employeeId = "employee_id"
        case title
        case hourlyRate = "hourly_rate"
    }

}

