/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** An employee created in the **Square Dashboard** account of a business.  Used by the Labor API. */

public struct Employee: Codable, Identifiable {

    /** UUID for this &#x60;Employee&#x60;. */
    public let id: String?
    /** Given (first) name of the employee. */
    public let firstName: String?
    /** Family (last) name of the employee */
    public let lastName: String?
    /** Email of the employee */
    public let email: String?
    /** Phone number of the employee in E.164 format, i.e. \&quot;+12125554250\&quot; */
    public let phoneNumber: String?
    /** A list of location IDs where this employee has access. */
    public let locationIds: [String]?
    /** Specifies the status of the employee being fetched. See [EmployeeStatus](#type-employeestatus) for possible values */
    public let status: EmployeeStatus?
    /** A read-only timestamp in RFC 3339 format. */
    public let createdAt: String?
    /** A read-only timestamp in RFC 3339 format. */
    public let updatedAt: String?

    public init(id: String?, firstName: String?, lastName: String?, email: String?, phoneNumber: String?, locationIds: [String]?, status: EmployeeStatus?, createdAt: String?, updatedAt: String?) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phoneNumber = phoneNumber
        self.locationIds = locationIds
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case phoneNumber = "phone_number"
        case locationIds = "location_ids"
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

}

