/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates which high-level category of error has occurred during a request to the Connect API. */
public enum ErrorCategory: String, Codable {
    case apiError = "API_ERROR"
    case authenticationError = "AUTHENTICATION_ERROR"
    case invalidRequestError = "INVALID_REQUEST_ERROR"
    case rateLimitError = "RATE_LIMIT_ERROR"
    case paymentMethodError = "PAYMENT_METHOD_ERROR"
    case refundError = "REFUND_ERROR"

}
