/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A response to a request to get an &#x60;EmployeeWage&#x60;. Contains the requested &#x60;EmployeeWage&#x60; objects. May contain a set of &#x60;Error&#x60; objects if the request resulted in errors. */

public struct GetEmployeeWageResponse: Codable {

    /** The requested &#x60;EmployeeWage&#x60; object. */
    public let employeeWage: EmployeeWage?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(employeeWage: EmployeeWage?, errors: [ModelError]?) {
        self.employeeWage = employeeWage
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case employeeWage = "employee_wage"
        case errors
    }

}

