/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates the state of a tracked item quantity in the lifecycle of goods. */
public enum InventoryState: String, Codable {
    case custom = "CUSTOM"
    case inStock = "IN_STOCK"
    case sold = "SOLD"
    case returnedByCustomer = "RETURNED_BY_CUSTOMER"
    case reservedForSale = "RESERVED_FOR_SALE"
    case soldOnline = "SOLD_ONLINE"
    case orderedFromVendor = "ORDERED_FROM_VENDOR"
    case receivedFromVendor = "RECEIVED_FROM_VENDOR"
    case inTransitTo = "IN_TRANSIT_TO"
    case _none = "NONE"
    case waste = "WASTE"
    case unlinkedReturn = "UNLINKED_RETURN"

}
