/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents the transfer of a quantity of product inventory at a particular time from one location to another. */

public struct InventoryTransfer: Codable, Identifiable {

    /** A unique ID generated by Square for the [InventoryTransfer](#type-inventorytransfer). */
    public let id: String?
    /** An optional ID provided by the application to tie the [InventoryTransfer](#type-inventorytransfer) to an external system. */
    public let referenceId: String?
    /** The [InventoryState](#type-inventorystate) for the quantity of items being transfered. See [InventoryState](#type-inventorystate) for possible values */
    public let state: InventoryState?
    /** The Square ID of the [Location](#type-location) where the related quantity of items were tracked before the transfer. */
    public let fromLocationId: String?
    /** The Square ID of the [Location](#type-location) where the related quantity of items were tracked after the transfer. */
    public let toLocationId: String?
    /** The Square generated ID of the [CatalogObject](#type-catalogobject) being tracked. */
    public let catalogObjectId: String?
    /** The [CatalogObjectType](#type-catalogobjecttype) of the [CatalogObject](#type-catalogobject) being tracked.Tracking is only supported for the &#x60;ITEM_VARIATION&#x60; type. */
    public let catalogObjectType: String?
    /** The number of items affected by the transfer as a decimal string. Can support up to 5 digits after the decimal point.  _Important_: The Point of Sale app and Dashboard do not currently support decimal quantities. If a Point of Sale app or Dashboard attempts to read a decimal quantity on inventory counts or adjustments, the quantity will be rounded down to the nearest integer. For example, &#x60;2.5&#x60; will become &#x60;2&#x60;, and &#x60;-2.5&#x60; will become &#x60;-3&#x60;.  Read [Decimal Quantities (BETA)](/orders-api/what-it-does#decimal-quantities) for more information. */
    public let quantity: String?
    /** A client-generated timestamp in RFC 3339 format that indicates when the transfer took place. For write actions, the &#x60;occurred_at&#x60; timestamp cannot be older than 24 hours or in the future relative to the time of the request. */
    public let occurredAt: String?
    /** A read-only timestamp in RFC 3339 format that indicates when Square received the transfer request. */
    public let createdAt: String?
    /** Read-only information about the application that initiated the inventory transfer. */
    public let source: SourceApplication?
    /** The Square ID of the [Employee](#type-employee) responsible for the inventory transfer. */
    public let employeeId: String?

    public init(id: String?, referenceId: String?, state: InventoryState?, fromLocationId: String?, toLocationId: String?, catalogObjectId: String?, catalogObjectType: String?, quantity: String?, occurredAt: String?, createdAt: String?, source: SourceApplication?, employeeId: String?) {
        self.id = id
        self.referenceId = referenceId
        self.state = state
        self.fromLocationId = fromLocationId
        self.toLocationId = toLocationId
        self.catalogObjectId = catalogObjectId
        self.catalogObjectType = catalogObjectType
        self.quantity = quantity
        self.occurredAt = occurredAt
        self.createdAt = createdAt
        self.source = source
        self.employeeId = employeeId
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case referenceId = "reference_id"
        case state
        case fromLocationId = "from_location_id"
        case toLocationId = "to_location_id"
        case catalogObjectId = "catalog_object_id"
        case catalogObjectType = "catalog_object_type"
        case quantity
        case occurredAt = "occurred_at"
        case createdAt = "created_at"
        case source
        case employeeId = "employee_id"
    }

}

