/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents a change in state or quantity of product inventory at a particular time and location. */

public struct InventoryAdjustment: Codable, Identifiable {

    /** A unique ID generated by Square for the [InventoryAdjustment](#type-inventoryadjustment). */
    public let id: String?
    /** An optional ID provided by the application to tie the [InventoryAdjustment](#type-inventoryadjustment) to an external system. */
    public let referenceId: String?
    /** The [InventoryState](#type-inventorystate) of the related quantity of items before the adjustment. See [InventoryState](#type-inventorystate) for possible values */
    public let fromState: InventoryState?
    /** The [InventoryState](#type-inventorystate) of the related quantity of items after the adjustment. See [InventoryState](#type-inventorystate) for possible values */
    public let toState: InventoryState?
    /** The Square ID of the [Location](#type-location) where the related quantity of items are being tracked. */
    public let locationId: String?
    /** The Square generated ID of the [CatalogObject](#type-catalogobject) being tracked. */
    public let catalogObjectId: String?
    /** The [CatalogObjectType](#type-catalogobjecttype) of the [CatalogObject](#type-catalogobject) being tracked. Tracking is only supported for the &#x60;ITEM_VARIATION&#x60; type. */
    public let catalogObjectType: String?
    /** The number of items affected by the adjustment as a decimal string. Can support up to 5 digits after the decimal point.  _Important_: The Point of Sale app and Dashboard do not currently support decimal quantities. If a Point of Sale app or Dashboard attempts to read a decimal quantity on inventory counts or adjustments, the quantity will be rounded down to the nearest integer. For example, &#x60;2.5&#x60; will become &#x60;2&#x60;, and &#x60;-2.5&#x60; will become &#x60;-3&#x60;.  Read [Decimal Quantities (BETA)](/orders-api/what-it-does#decimal-quantities) for more information. */
    public let quantity: String?
    /** The read-only total price paid for goods associated with the adjustment. Present if and only if &#x60;to_state&#x60; is &#x60;SOLD&#x60;. Always non-negative. */
    public let totalPriceMoney: Money?
    /** A client-generated timestamp in RFC 3339 format that indicates when the adjustment took place. For write actions, the &#x60;occurred_at&#x60; timestamp cannot be older than 24 hours or in the future relative to the time of the request. */
    public let occurredAt: String?
    /** A read-only timestamp in RFC 3339 format that indicates when Square received the adjustment. */
    public let createdAt: String?
    /** Read-only information about the application that caused the inventory adjustment. */
    public let source: SourceApplication?
    /** The Square ID of the [Employee](#type-employee) responsible for the inventory adjustment. */
    public let employeeId: String?
    /** The read-only Square ID of the [Transaction][#type-transaction] that caused the adjustment. Only relevant for payment-related state transitions. */
    public let transactionId: String?
    /** The read-only Square ID of the [Refund][#type-refund] that caused the adjustment. Only relevant for refund-related state transitions. */
    public let refundId: String?
    /** The read-only Square ID of the purchase order that caused the adjustment. Only relevant for state transitions from the Square for Retail app. */
    public let purchaseOrderId: String?
    /** The read-only Square ID of the Square goods receipt that caused the adjustment. Only relevant for state transitions from the Square for Retail app. */
    public let goodsReceiptId: String?

    public init(id: String?, referenceId: String?, fromState: InventoryState?, toState: InventoryState?, locationId: String?, catalogObjectId: String?, catalogObjectType: String?, quantity: String?, totalPriceMoney: Money?, occurredAt: String?, createdAt: String?, source: SourceApplication?, employeeId: String?, transactionId: String?, refundId: String?, purchaseOrderId: String?, goodsReceiptId: String?) {
        self.id = id
        self.referenceId = referenceId
        self.fromState = fromState
        self.toState = toState
        self.locationId = locationId
        self.catalogObjectId = catalogObjectId
        self.catalogObjectType = catalogObjectType
        self.quantity = quantity
        self.totalPriceMoney = totalPriceMoney
        self.occurredAt = occurredAt
        self.createdAt = createdAt
        self.source = source
        self.employeeId = employeeId
        self.transactionId = transactionId
        self.refundId = refundId
        self.purchaseOrderId = purchaseOrderId
        self.goodsReceiptId = goodsReceiptId
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case referenceId = "reference_id"
        case fromState = "from_state"
        case toState = "to_state"
        case locationId = "location_id"
        case catalogObjectId = "catalog_object_id"
        case catalogObjectType = "catalog_object_type"
        case quantity
        case totalPriceMoney = "total_price_money"
        case occurredAt = "occurred_at"
        case createdAt = "created_at"
        case source
        case employeeId = "employee_id"
        case transactionId = "transaction_id"
        case refundId = "refund_id"
        case purchaseOrderId = "purchase_order_id"
        case goodsReceiptId = "goods_receipt_id"
    }

}

