/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The response to a request for a set of &#x60;WorkweekConfig&#x60; objects. Contains the requested &#x60;WorkweekConfig&#x60; objects. May contain a set of &#x60;Error&#x60; objects if the request resulted in errors. */

public struct ListWorkweekConfigsResponse: Codable {

    /** A page of Employee Wage results. */
    public let workweekConfigs: [WorkweekConfig]?
    /** Value supplied in the subsequent request to fetch the next page of Employee Wage results. */
    public let cursor: String?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(workweekConfigs: [WorkweekConfig]?, cursor: String?, errors: [ModelError]?) {
        self.workweekConfigs = workweekConfigs
        self.cursor = cursor
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case workweekConfigs = "workweek_configs"
        case cursor
        case errors
    }

}

