/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A request for a filtered set of &#x60;BreakType&#x60; objects */

public struct ListBreakTypesRequest: Codable {

    /** Filter Break Types returned to only those that are associated with the specified location. */
    public let locationId: String?
    /** Maximum number of Break Types to return per page. Can range between 1 and 200. The default is the maximum at 200. */
    public let limit: Int?
    /** Pointer to the next page of Break Type results to fetch. */
    public let cursor: String?

    public init(locationId: String?, limit: Int?, cursor: String?) {
        self.locationId = locationId
        self.limit = limit
        self.cursor = cursor
    }

    public enum CodingKeys: String, CodingKey { 
        case locationId = "location_id"
        case limit
        case cursor
    }

}

