/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The response to a request for a set of &#x60;EmployeeWage&#x60; objects. Contains  a set of &#x60;EmployeeWage&#x60;. */

public struct ListEmployeeWagesResponse: Codable {

    /** A page of Employee Wage results. */
    public let employeeWages: [EmployeeWage]?
    /** Value supplied in the subsequent request to fetch the next next page of Employee Wage results. */
    public let cursor: String?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(employeeWages: [EmployeeWage]?, cursor: String?, errors: [ModelError]?) {
        self.employeeWages = employeeWages
        self.cursor = cursor
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case employeeWages = "employee_wages"
        case cursor
        case errors
    }

}

