/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the response body of a request to the [ListPayments](#endpoint-payments-listpayments) endpoint. */

public struct ListPaymentsResponse: Codable {

    /** Information on errors encountered during the request. */
    public let errors: [ModelError]?
    /** The requested list of &#x60;Payment&#x60;s. */
    public let payments: [Payment]?
    /** The pagination cursor to be used in a subsequent request. If empty, this is the final response.  See [Pagination](/basics/api101/pagination) for more information. */
    public let cursor: String?

    public init(errors: [ModelError]?, payments: [Payment]?, cursor: String?) {
        self.errors = errors
        self.payments = payments
        self.cursor = cursor
    }

}

