/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the response body of a request to the ListCustomers endpoint.  One of &#x60;errors&#x60; or &#x60;customers&#x60; is present in a given response (never both). */

public struct ListCustomersResponse: Codable {

    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?
    /** An array of &#x60;Customer&#x60; objects that match your query. */
    public let customers: [Customer]?
    /** A pagination cursor to retrieve the next set of results for your original query to the endpoint. This value is present only if the request succeeded and additional results are available.  See [Pagination](/basics/api101/pagination) for more information. */
    public let cursor: String?

    public init(errors: [ModelError]?, customers: [Customer]?, cursor: String?) {
        self.errors = errors
        self.customers = customers
        self.cursor = cursor
    }

}

