/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Retrieve a paged-list of employees for a Square account */

public struct ListEmployeesRequest: Codable {

    /** Filter employees returned to only those that are associated with the specified location. */
    public let locationId: String?
    /** Specifies the EmployeeStatus to filter the employee by. See [EmployeeStatus](#type-employeestatus) for possible values */
    public let status: EmployeeStatus?
    /** The number of employees to be returned on each page. */
    public let limit: Int?
    /** The token required to retrieve the specified page of results. */
    public let cursor: String?

    public init(locationId: String?, status: EmployeeStatus?, limit: Int?, cursor: String?) {
        self.locationId = locationId
        self.status = status
        self.limit = limit
        self.cursor = cursor
    }

    public enum CodingKeys: String, CodingKey { 
        case locationId = "location_id"
        case status
        case limit
        case cursor
    }

}

