/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the response body of a request to the ListEmployees endpoint.  One of &#x60;errors&#x60; or &#x60;employees&#x60; is present in a given response (never both). */

public struct ListEmployeesResponse: Codable {

    /** List of employees returned from the request. */
    public let employees: [Employee]?
    /** The token to be used to retrieve the next page of results. */
    public let cursor: String?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(employees: [Employee]?, cursor: String?, errors: [ModelError]?) {
        self.employees = employees
        self.cursor = cursor
        self.errors = errors
    }

}

