/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A request for a set of &#x60;EmployeeWage&#x60; objects */

public struct ListEmployeeWagesRequest: Codable {

    /** Filter wages returned to only those that are associated with the specified employee. */
    public let employeeId: String?
    /** Maximum number of Employee Wages to return per page. Can range between 1 and 200. The default is the maximum at 200. */
    public let limit: Int?
    /** Pointer to the next page of Employee Wage results to fetch. */
    public let cursor: String?

    public init(employeeId: String?, limit: Int?, cursor: String?) {
        self.employeeId = employeeId
        self.limit = limit
        self.cursor = cursor
    }

    public enum CodingKeys: String, CodingKey { 
        case employeeId = "employee_id"
        case limit
        case cursor
    }

}

