/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A request for a set of &#x60;WorkweekConfig&#x60; objects */

public struct ListWorkweekConfigsRequest: Codable {

    /** Maximum number of Workweek Configs to return per page. */
    public let limit: Int?
    /** Pointer to the next page of Workweek Config results to fetch. */
    public let cursor: String?

    public init(limit: Int?, cursor: String?) {
        self.limit = limit
        self.cursor = cursor
    }

}

