/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The response to a request for a set of &#x60;BreakTypes&#x60;. Contains the requested &#x60;BreakType&#x60; objects. May contain a set of &#x60;Error&#x60; objects if the request resulted in errors. */

public struct ListBreakTypesResponse: Codable {

    /**  A page of &#x60;BreakType&#x60; results. */
    public let breakTypes: [BreakType]?
    /** Value supplied in the subsequent request to fetch the next next page of Break Type results. */
    public let cursor: String?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(breakTypes: [BreakType]?, cursor: String?, errors: [ModelError]?) {
        self.breakTypes = breakTypes
        self.cursor = cursor
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case breakTypes = "break_types"
        case cursor
        case errors
    }

}

