/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates payment capabilities that a business&#39;s location might or might not have enabled. */
public enum LocationCapability: String, Codable {
    case creditCardProcessing = "CREDIT_CARD_PROCESSING"

}
