/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Describes the type of this unit and indicates which field contains the unit information. This is an ‘open’ enum. */
public enum MeasurementUnitUnitType: String, Codable {
    case custom = "TYPE_CUSTOM"
    case area = "TYPE_AREA"
    case length = "TYPE_LENGTH"
    case volume = "TYPE_VOLUME"
    case weight = "TYPE_WEIGHT"
    case generic = "TYPE_GENERIC"

}
