/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Unit of area used to measure a quantity. */
public enum MeasurementUnitArea: String, Codable {
    case imperialAcre = "IMPERIAL_ACRE"
    case imperialSquareInch = "IMPERIAL_SQUARE_INCH"
    case imperialSquareFoot = "IMPERIAL_SQUARE_FOOT"
    case imperialSquareYard = "IMPERIAL_SQUARE_YARD"
    case imperialSquareMile = "IMPERIAL_SQUARE_MILE"
    case metricSquareCentimeter = "METRIC_SQUARE_CENTIMETER"
    case metricSquareMeter = "METRIC_SQUARE_METER"
    case metricSquareKilometer = "METRIC_SQUARE_KILOMETER"

}
