/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The information needed to define a custom unit, provided by the seller. */

public struct MeasurementUnitCustom: Codable {

    /** The name of the custom unit, for example \&quot;bushel\&quot;. */
    public let name: String
    /** The abbreviation of the custom unit, such as \&quot;bsh\&quot; (bushel). This appears in the cart for the Point of Sale app, and in reports. */
    public let abbreviation: String

    public init(name: String, abbreviation: String) {
        self.name = name
        self.abbreviation = abbreviation
    }

}

