/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents an error encountered during a request to the Connect API. */

public struct ModelError: Codable {

    /** The high-level category for the error. See [ErrorCategory](#type-errorcategory) See [ErrorCategory](#type-errorcategory) for possible values */
    public let category: ErrorCategory
    /** The specific code of the error. See [ErrorCode](#type-errorcode) for possible See [ErrorCode](#type-errorcode) for possible values */
    public let code: ErrorCode
    /** A human-readable description of the error for debugging purposes. */
    public let detail: String?
    /** The name of the field provided in the original request (if any) that the error pertains to. */
    public let field: String?

    public init(category: ErrorCategory, code: ErrorCode, detail: String?, field: String?) {
        self.category = category
        self.code = code
        self.detail = detail
        self.field = field
    }

}

