/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct ObtainTokenResponse: Codable {

    /** A valid OAuth access token. OAuth access tokens are 64 bytes long. Provide the access token in a header with every request to Connect API endpoints. See the [Build with OAuth](/authz/oauth/build-with-the-api) guide for more information. */
    public let accessToken: String?
    /** This value is always _bearer_. */
    public let tokenType: String?
    /** The date when access_token expires, in [ISO 8601](http://www.iso.org/iso/home/standards/iso8601.htm) format. */
    public let expiresAt: String?
    /** The ID of the authorizing merchant&#39;s business. */
    public let merchantId: String?
    /** __LEGACY FIELD__. The ID of a subscription plan the merchant signed up for. Only present if the merchant signed up for a subscription during authorization. */
    public let subscriptionId: String?
    /** __LEGACY FIELD__. The ID of the subscription plan the merchant signed up for. Only present if the merchant signed up for a subscription during authorization. */
    public let planId: String?
    /** Then OpenID token belonging to this this person. Only present if the OPENID scope is included in the authorize request. */
    public let idToken: String?
    /** A refresh token. For more information, see [OAuth access token management](/authz/oauth/how-it-works#oauth-access-token-management). */
    public let refreshToken: String?

    public init(accessToken: String?, tokenType: String?, expiresAt: String?, merchantId: String?, subscriptionId: String?, planId: String?, idToken: String?, refreshToken: String?) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresAt = expiresAt
        self.merchantId = merchantId
        self.subscriptionId = subscriptionId
        self.planId = planId
        self.idToken = idToken
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey { 
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresAt = "expires_at"
        case merchantId = "merchant_id"
        case subscriptionId = "subscription_id"
        case planId = "plan_id"
        case idToken = "id_token"
        case refreshToken = "refresh_token"
    }

}

