/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates whether this is a line item or order level tax. */
public enum OrderLineItemTaxScope: String, Codable {
    case otherTaxScope = "OTHER_TAX_SCOPE"
    case lineItem = "LINE_ITEM"
    case order = "ORDER"

}
