/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Contains the measurement unit for a quantity and a precision which specifies the number of digits after the decimal point for decimal quantities. */

public struct OrderQuantityUnit: Codable {

    /** A [MeasurementUnit](#type-measurementunit) that represents the unit of measure for the quantity. */
    public let measurementUnit: MeasurementUnit?
    /** For non-integer quantities, represents the number of digits after the decimal point that are recorded for this quantity.  For example, a precision of 1 allows quantities like &#x60;\&quot;1.0\&quot;&#x60; and &#x60;\&quot;1.1\&quot;&#x60;, but not &#x60;\&quot;1.01\&quot;&#x60;.  Min: 0. Max: 5. */
    public let precision: Int?

    public init(measurementUnit: MeasurementUnit?, precision: Int?) {
        self.measurementUnit = measurementUnit
        self.precision = precision
    }

    public enum CodingKeys: String, CodingKey { 
        case measurementUnit = "measurement_unit"
        case precision
    }

}

