/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A lightweight description of an [Order](#type-order) that is returned when &#x60;returned_entries&#x60; is true on a [SearchOrderRequest](#type-searchorderrequest) */

public struct OrderEntry: Codable {

    /** The id of the Order */
    public let orderId: String?
    /** Version number which is incremented each time an update is committed to the order. Orders that were not created through the API will not include a version and thus cannot be updated.  [Read more about working with versions](/orders-api/manage-orders#update-orders). */
    public let version: Int?
    /** The location id the Order belongs to. */
    public let locationId: String?

    public init(orderId: String?, version: Int?, locationId: String?) {
        self.orderId = orderId
        self.version = version
        self.locationId = locationId
    }

    public enum CodingKeys: String, CodingKey { 
        case orderId = "order_id"
        case version
        case locationId = "location_id"
    }

}

