/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Contains details on how to fulfill this order. */

public struct OrderFulfillment: Codable {

    /** Unique ID that identifies the fulfillment only within this order. */
    public let uid: String?
    /** The type of the fulfillment. See [OrderFulfillmentType](#type-orderfulfillmenttype) for possible values */
    public let type: OrderFulfillmentType?
    /** The state of the fulfillment. See [OrderFulfillmentState](#type-orderfulfillmentstate) for possible values */
    public let state: OrderFulfillmentState?
    /** Contains details for a pickup fulfillment. Required when fulfillment type is &#x60;PICKUP&#x60;. */
    public let pickupDetails: OrderFulfillmentPickupDetails?
    /** Contains details for a shipment fulfillment. Required when fulfillment type is &#x60;SHIPMENT&#x60;.  A shipment fulfillment&#39;s relationship to fulfillment &#x60;state&#x60;: &#x60;PROPOSED&#x60;: A shipment is requested. &#x60;RESERVED&#x60;: Fulfillment accepted. Shipment processing. &#x60;PREPARED&#x60;: Shipment packaged. Shipping label created. &#x60;COMPLETED&#x60;: Package has been shipped. &#x60;CANCELED&#x60;: Shipment has been canceled. &#x60;FAILED&#x60;: Shipment has failed. */
    public let shipmentDetails: OrderFulfillmentShipmentDetails?

    public init(uid: String?, type: OrderFulfillmentType?, state: OrderFulfillmentState?, pickupDetails: OrderFulfillmentPickupDetails?, shipmentDetails: OrderFulfillmentShipmentDetails?) {
        self.uid = uid
        self.type = type
        self.state = state
        self.pickupDetails = pickupDetails
        self.shipmentDetails = shipmentDetails
    }

    public enum CodingKeys: String, CodingKey { 
        case uid
        case type
        case state
        case pickupDetails = "pickup_details"
        case shipmentDetails = "shipment_details"
    }

}

