/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents a phase in the process of calculating order totals. Service charges are applied __after__ the indicated phase.  [Read more about how order totals are calculated.](/docs/orders-api/how-it-works#how-totals-are-calculated) */
public enum OrderServiceChargeCalculationPhase: String, Codable {
    case subtotalPhase = "SUBTOTAL_PHASE"
    case totalPhase = "TOTAL_PHASE"

}
