/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The set of line items, service charges, taxes, discounts, tips, etc. being returned in an Order. */

public struct OrderReturn: Codable {

    /** Unique ID that identifies the return only within this order. */
    public let uid: String?
    /** Order which contains the original sale of these returned line items. This will be unset for unlinked returns. */
    public let sourceOrderId: String?
    /** Collection of line items which are being returned. */
    public let returnLineItems: [OrderReturnLineItem]?
    /** Collection of service charges which are being returned. */
    public let returnServiceCharges: [OrderReturnServiceCharge]?
    /** Collection of references to taxes being returned for an order, including the total applied tax amount to be returned. The taxes must reference a top-level tax ID from the source order. */
    public let returnTaxes: [OrderReturnTax]?
    /** Collection of references to discounts being returned for an order, including the total applied discount amount to be returned. The discounts must reference a top-level discount ID from the source order. */
    public let returnDiscounts: [OrderReturnDiscount]?
    /** A positive or negative rounding adjustment to the total value being returned. Commonly used to apply Cash Rounding when the minimum unit of account is smaller than the lowest physical denomination of currency. */
    public let roundingAdjustment: OrderRoundingAdjustment?
    /** Aggregate monetary value being returned by this Return entry. */
    public let returnAmounts: OrderMoneyAmounts?

    public init(uid: String?, sourceOrderId: String?, returnLineItems: [OrderReturnLineItem]?, returnServiceCharges: [OrderReturnServiceCharge]?, returnTaxes: [OrderReturnTax]?, returnDiscounts: [OrderReturnDiscount]?, roundingAdjustment: OrderRoundingAdjustment?, returnAmounts: OrderMoneyAmounts?) {
        self.uid = uid
        self.sourceOrderId = sourceOrderId
        self.returnLineItems = returnLineItems
        self.returnServiceCharges = returnServiceCharges
        self.returnTaxes = returnTaxes
        self.returnDiscounts = returnDiscounts
        self.roundingAdjustment = roundingAdjustment
        self.returnAmounts = returnAmounts
    }

    public enum CodingKeys: String, CodingKey { 
        case uid
        case sourceOrderId = "source_order_id"
        case returnLineItems = "return_line_items"
        case returnServiceCharges = "return_service_charges"
        case returnTaxes = "return_taxes"
        case returnDiscounts = "return_discounts"
        case roundingAdjustment = "rounding_adjustment"
        case returnAmounts = "return_amounts"
    }

}

