/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Indicates how the tax is applied to the associated line item or order. */
public enum OrderLineItemTaxType: String, Codable {
    case unknownTax = "UNKNOWN_TAX"
    case additive = "ADDITIVE"
    case inclusive = "INCLUSIVE"

}
