/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents the origination details of an order. */

public struct OrderSource: Codable {

    /** The name used to identify the place (physical or digital) that an order originates. If unset, the name defaults to the name of the application that created the order. */
    public let name: String?

    public init(name: String?) {
        self.name = name
    }

}

