/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the parameters that can be included in the body of a request to the RegisterDomain endpoint. */

public struct RegisterDomainRequest: Codable {

    /** A domain name as described in RFC-1034 that will be registered with ApplePay */
    public let domainName: String

    public init(domainName: String) {
        self.domainName = domainName
    }

    public enum CodingKeys: String, CodingKey { 
        case domainName = "domain_name"
    }

}

