/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the response body of a request to the RegisterDomain endpoint.  Either &#x60;errors&#x60; or &#x60;status&#x60; will be present in a given response (never both). */

public struct RegisterDomainResponse: Codable {

    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?
    /** Status of the domain registration. See [RegisterDomainResponseStatus](#type-registerdomainresponsestatus) for possible values */
    public let status: RegisterDomainResponseStatus?

    public init(errors: [ModelError]?, status: RegisterDomainResponseStatus?) {
        self.errors = errors
        self.status = status
    }

}

