/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct RenewTokenResponse: Codable {

    /** The renewed access token. This value might be different from the &#x60;access_token&#x60; you provided in your request. You provide this token in a header with every request to Connect API endpoints. See [Request and response headers](https://docs.connect.squareup.com/api/connect/v2/#requestandresponseheaders) for the format of this header. */
    public let accessToken: String?
    /** This value is always _bearer_. */
    public let tokenType: String?
    /** The date when access_token expires, in [ISO 8601](http://www.iso.org/iso/home/standards/iso8601.htm) format. */
    public let expiresAt: String?
    /** The ID of the authorizing merchant&#39;s business. */
    public let merchantId: String?
    /** __LEGACY FIELD__. The ID of the merchant subscription associated with the authorization. Only present if the merchant signed up for a subscription during authorization. */
    public let subscriptionId: String?
    /** __LEGACY FIELD__. The ID of the subscription plan the merchant signed up for. Only present if the merchant signed up for a subscription during authorization. */
    public let planId: String?

    public init(accessToken: String?, tokenType: String?, expiresAt: String?, merchantId: String?, subscriptionId: String?, planId: String?) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresAt = expiresAt
        self.merchantId = merchantId
        self.subscriptionId = subscriptionId
        self.planId = planId
    }

    public enum CodingKeys: String, CodingKey { 
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresAt = "expires_at"
        case merchantId = "merchant_id"
        case subscriptionId = "subscription_id"
        case planId = "plan_id"
    }

}

