/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct RetrieveCatalogObjectResponse: Codable {

    /** The set of [Error](#type-error)s encountered. */
    public let errors: [ModelError]?
    /** The [CatalogObject](#type-catalogobject)s returned. */
    public let object: CatalogObject?
    /** A list of [CatalogObject](#type-catalogobject)s referenced by the object in the &#x60;object&#x60; field. */
    public let relatedObjects: [CatalogObject]?

    public init(errors: [ModelError]?, object: CatalogObject?, relatedObjects: [CatalogObject]?) {
        self.errors = errors
        self.object = object
        self.relatedObjects = relatedObjects
    }

    public enum CodingKeys: String, CodingKey { 
        case errors
        case object
        case relatedObjects = "related_objects"
    }

}

