/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct RevokeTokenRequest: Codable {

    /** Your application&#39;s ID, available from the [application dashboard](https://connect.squareup.com/apps). */
    public let clientId: String?
    /** The access token of the merchant whose token you want to revoke. Do not provide a value for merchant_id if you provide this parameter. */
    public let accessToken: String?
    /** The ID of the merchant whose token you want to revoke. Do not provide a value for access_token if you provide this parameter. */
    public let merchantId: String?

    public init(clientId: String?, accessToken: String?, merchantId: String?) {
        self.clientId = clientId
        self.accessToken = accessToken
        self.merchantId = merchantId
    }

    public enum CodingKeys: String, CodingKey { 
        case clientId = "client_id"
        case accessToken = "access_token"
        case merchantId = "merchant_id"
    }

}

