/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Filter based on order &#x60;source&#x60; information. */

public struct SearchOrdersSourceFilter: Codable {

    /** Filters by [Source](#type-ordersource) &#x60;name&#x60;. Will return any orders with with a &#x60;source.name&#x60; that matches any of the listed source names.  Max: 10 source names. */
    public let sourceNames: [String]?

    public init(sourceNames: [String]?) {
        self.sourceNames = sourceNames
    }

    public enum CodingKeys: String, CodingKey { 
        case sourceNames = "source_names"
    }

}

