/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A request for a filtered and sorted set of &#x60;Shift&#x60; objects. */

public struct SearchShiftsRequest: Codable {

    /** Query filters. */
    public let query: ShiftQuery?
    /** number of resources in a page (200 by default). */
    public let limit: Int?
    /** opaque cursor for fetching the next page. */
    public let cursor: String?

    public init(query: ShiftQuery?, limit: Int?, cursor: String?) {
        self.query = query
        self.limit = limit
        self.cursor = cursor
    }

}

