/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Filtering criteria to use for a SearchOrders request. Multiple filters will be ANDed together. */

public struct SearchOrdersFilter: Codable {

    /** Filter by [&#x60;OrderState&#x60;](#type-orderstate). */
    public let stateFilter: SearchOrdersStateFilter?
    /** Filter for results within a time range.  __Important:__ If you filter for orders by time range, you must set SearchOrdersSort to sort by the same field. [Learn more about filtering orders by time range](/orders-api/manage-orders#important-note-on-filtering-orders-by-time-range) */
    public let dateTimeFilter: SearchOrdersDateTimeFilter?
    /** Filter by fulfillment type or state. */
    public let fulfillmentFilter: SearchOrdersFulfillmentFilter?
    /** Filter by source of order. */
    public let sourceFilter: SearchOrdersSourceFilter?
    /** Filter by customers associated with the order. */
    public let customerFilter: SearchOrdersCustomerFilter?

    public init(stateFilter: SearchOrdersStateFilter?, dateTimeFilter: SearchOrdersDateTimeFilter?, fulfillmentFilter: SearchOrdersFulfillmentFilter?, sourceFilter: SearchOrdersSourceFilter?, customerFilter: SearchOrdersCustomerFilter?) {
        self.stateFilter = stateFilter
        self.dateTimeFilter = dateTimeFilter
        self.fulfillmentFilter = fulfillmentFilter
        self.sourceFilter = sourceFilter
        self.customerFilter = customerFilter
    }

    public enum CodingKeys: String, CodingKey { 
        case stateFilter = "state_filter"
        case dateTimeFilter = "date_time_filter"
        case fulfillmentFilter = "fulfillment_filter"
        case sourceFilter = "source_filter"
        case customerFilter = "customer_filter"
    }

}

