/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Filter based on Order &#x60;customer_id&#x60; and any Tender &#x60;customer_id&#x60; associated with the Order. Does not filter based on the [FulfillmentRecipient](#type-orderfulfillmentrecipient) &#x60;customer_id&#x60;. */

public struct SearchOrdersCustomerFilter: Codable {

    /** List of customer IDs to filter by.  Max: 10 customer IDs. */
    public let customerIds: [String]?

    public init(customerIds: [String]?) {
        self.customerIds = customerIds
    }

    public enum CodingKeys: String, CodingKey { 
        case customerIds = "customer_ids"
    }

}

