/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Filter based on [Order Fulfillment](#type-orderfulfillment) information. */

public struct SearchOrdersFulfillmentFilter: Codable {

    /** List of [fulfillment types](#type-orderfulfillmenttype) to filter for. Will return orders if any of its fulfillments match any of the fulfillment types listed in this field. See [OrderFulfillmentType](#type-orderfulfillmenttype) for possible values */
    public let fulfillmentTypes: [OrderFulfillmentType]
    /** List of [fulfillment states](#type-orderfulfillmentstate) to filter for. Will return orders if any of its fulfillments match any of the fulfillment states listed in this field. See [OrderFulfillmentState](#type-orderfulfillmentstate) for possible values */
    public let fulfillmentStates: [OrderFulfillmentState]?

    public init(fulfillmentTypes: [OrderFulfillmentType], fulfillmentStates: [OrderFulfillmentState]?) {
        self.fulfillmentTypes = fulfillmentTypes
        self.fulfillmentStates = fulfillmentStates
    }

    public enum CodingKeys: String, CodingKey { 
        case fulfillmentTypes = "fulfillment_types"
        case fulfillmentStates = "fulfillment_states"
    }

}

