/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in the response body of a request to the SearchCustomers endpoint.  One of &#x60;errors&#x60; or &#x60;customers&#x60; is present in a given response (never both). */

public struct SearchCustomersResponse: Codable {

    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?
    /** An array of &#x60;Customer&#x60; objects that match a query. */
    public let customers: [Customer]?
    /** A pagination cursor that can be used during subsequent calls to SearchCustomers to retrieve the next set of results associated with the original query. Pagination cursors are only present when a request succeeds and additional results are available.  See [Pagination](/basics/api101/pagination) for more information. */
    public let cursor: String?

    public init(errors: [ModelError]?, customers: [Customer]?, cursor: String?) {
        self.errors = errors
        self.customers = customers
        self.cursor = cursor
    }

}

