/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Filter by current Order &#x60;state&#x60;. */

public struct SearchOrdersStateFilter: Codable {

    /** States to filter for. See [OrderState](#type-orderstate) for possible values */
    public let states: [OrderState]

    public init(states: [OrderState]) {
        self.states = states
    }

}

