/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The hourly wage rate used to compensate an employee for this shift. */

public struct ShiftWage: Codable {

    /** The name of the job performed during this shift. Square labor-reporting UIs may group shifts together by title. */
    public let title: String?
    /** Can be a custom-set hourly wage or the calculated effective hourly wage based on annual wage and hours worked per week. */
    public let hourlyRate: Money?

    public init(title: String?, hourlyRate: Money?) {
        self.title = title
        self.hourlyRate = hourlyRate
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case hourlyRate = "hourly_rate"
    }

}

