/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Sets the sort order of search results. */

public struct ShiftSort: Codable {

    /** The field to sort on. See [ShiftSortField](#type-shiftsortfield) for possible values */
    public let field: ShiftSortField?
    /** The order in which results are returned. Defaults to DESC. See [SortOrder](#type-sortorder) for possible values */
    public let order: SortOrder?

    public init(field: ShiftSortField?, order: SortOrder?) {
        self.field = field
        self.order = order
    }

}

