/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the logic used to apply a workday filter. */
public enum ShiftWorkdayMatcher: String, Codable {
    case startAt = "START_AT"
    case endAt = "END_AT"
    case intersection = "INTERSECTION"

}
