/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A &#x60;Shift&#x60; search query filter parameter that sets a range of days that  a &#x60;Shift&#x60; must start or end in before passing the filter condition. */

public struct ShiftWorkday: Codable {

    /** Dates for fetching the shifts */
    public let dateRange: DateRange?
    /** The strategy on which the dates are applied. See [ShiftWorkdayMatcher](#type-shiftworkdaymatcher) for possible values */
    public let matchShiftsBy: ShiftWorkdayMatcher?
    /** Location-specific timezones convert workdays to datetime filters. Every location included in the query must have a timezone, or this field must be provided as a fallback. Format: the IANA timezone database identifier for the relevant timezone. */
    public let defaultTimezone: String?

    public init(dateRange: DateRange?, matchShiftsBy: ShiftWorkdayMatcher?, defaultTimezone: String?) {
        self.dateRange = dateRange
        self.matchShiftsBy = matchShiftsBy
        self.defaultTimezone = defaultTimezone
    }

    public enum CodingKeys: String, CodingKey { 
        case dateRange = "date_range"
        case matchShiftsBy = "match_shifts_by"
        case defaultTimezone = "default_timezone"
    }

}

