/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Group of standard measurement units. */

public struct StandardUnitDescriptionGroup: Codable {

    /** List of measurement units in this description group. */
    public let standardUnitDescriptions: [StandardUnitDescription]?
    /** IETF language tag. */
    public let languageCode: String?

    public init(standardUnitDescriptions: [StandardUnitDescription]?, languageCode: String?) {
        self.standardUnitDescriptions = standardUnitDescriptions
        self.languageCode = languageCode
    }

    public enum CodingKeys: String, CodingKey { 
        case standardUnitDescriptions = "standard_unit_descriptions"
        case languageCode = "language_code"
    }

}

