/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** The response to a request to update a &#x60;WorkweekConfig&#x60; object. Contains the updated &#x60;WorkweekConfig&#x60; object. May contain a set of &#x60;Error&#x60; objects if the request resulted in errors. */

public struct UpdateWorkweekConfigResponse: Codable {

    /** The response object. */
    public let workweekConfig: WorkweekConfig?
    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?

    public init(workweekConfig: WorkweekConfig?, errors: [ModelError]?) {
        self.workweekConfig = workweekConfig
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case workweekConfig = "workweek_config"
        case errors
    }

}

