/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct UpdateItemTaxesRequest: Codable {

    /** The [CatalogItem](#type-catalogitem)s whose enabled/disabled [CatalogTax](#type-catalogtax)es are being updated. */
    public let itemIds: [String]
    /** The set of [CatalogTax](#type-catalogtax)es (referenced by ID) to enable for the [CatalogItem](#type-catalogitem). */
    public let taxesToEnable: [String]?
    /** The set of [CatalogTax](#type-catalogtax)es (referenced by ID) to disable for the [CatalogItem](#type-catalogitem). */
    public let taxesToDisable: [String]?

    public init(itemIds: [String], taxesToEnable: [String]?, taxesToDisable: [String]?) {
        self.itemIds = itemIds
        self.taxesToEnable = taxesToEnable
        self.taxesToDisable = taxesToDisable
    }

    public enum CodingKeys: String, CodingKey { 
        case itemIds = "item_ids"
        case taxesToEnable = "taxes_to_enable"
        case taxesToDisable = "taxes_to_disable"
    }

}

