/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct UpdateItemModifierListsRequest: Codable {

    /** The [CatalogItem](#type-catalogitem)s whose [CatalogModifierList](#type-catalogmodifierlist)s are being updated. */
    public let itemIds: [String]
    /** The set of [CatalogModifierList](#type-catalogmodifierlist)s (referenced by ID) to enable for the [CatalogItem](#type-catalogitem). */
    public let modifierListsToEnable: [String]?
    /** The set of [CatalogModifierList](#type-catalogmodifierlist)s (referenced by ID) to disable for the [CatalogItem](#type-catalogitem). */
    public let modifierListsToDisable: [String]?

    public init(itemIds: [String], modifierListsToEnable: [String]?, modifierListsToDisable: [String]?) {
        self.itemIds = itemIds
        self.modifierListsToEnable = modifierListsToEnable
        self.modifierListsToDisable = modifierListsToDisable
    }

    public enum CodingKeys: String, CodingKey { 
        case itemIds = "item_ids"
        case modifierListsToEnable = "modifier_lists_to_enable"
        case modifierListsToDisable = "modifier_lists_to_disable"
    }

}

