/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** A request to update a &#x60;WorkweekConfig&#x60; object */

public struct UpdateWorkweekConfigRequest: Codable {

    /** The updated &#x60;WorkweekConfig&#x60; object. */
    public let workweekConfig: WorkweekConfig?

    public init(workweekConfig: WorkweekConfig?) {
        self.workweekConfig = workweekConfig
    }

    public enum CodingKeys: String, CodingKey { 
        case workweekConfig = "workweek_config"
    }

}

