/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Defines the fields that are included in requests to the [UpdateOrder](#endpoint-orders-updateorder) endpoint. */

public struct UpdateOrderRequest: Codable {

    /** The [sparse order](/orders-api/manage-orders#sparse-order-objects) containing only the fields to update and the version the update is being applied to. */
    public let order: Order?
    /** The [dot notation paths](/orders-api/manage-orders#on-dot-notation) fields to clear. For example, &#x60;line_items[uid].note&#x60; [Read more about Deleting fields](/orders-api/manage-orders#delete-fields). */
    public let fieldsToClear: [String]?
    /** A value you specify that uniquely identifies this update request  If you&#39;re unsure whether a particular update was applied to an order successfully, you can reattempt it with the same idempotency key without worrying about creating duplicate updates to the order. The latest order version will be returned.  See [Idempotency](/basics/api101/idempotency) for more information. */
    public let idempotencyKey: String?

    public init(order: Order?, fieldsToClear: [String]?, idempotencyKey: String?) {
        self.order = order
        self.fieldsToClear = fieldsToClear
        self.idempotencyKey = idempotencyKey
    }

    public enum CodingKeys: String, CodingKey { 
        case order
        case fieldsToClear = "fields_to_clear"
        case idempotencyKey = "idempotency_key"
    }

}

