/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct UpsertCatalogObjectRequest: Codable {

    /** A value you specify that uniquely identifies this request among all your requests. A common way to create a valid idempotency key is to use a Universally unique identifier (UUID).  If you&#39;re unsure whether a particular request was successful, you can reattempt it with the same idempotency key without worrying about creating duplicate objects.  See [Idempotency](/basics/api101/idempotency) for more information. */
    public let idempotencyKey: String
    /** A [CatalogObject](#type-catalogobject) to be created or updated. - For updates, the object must be active (the &#x60;is_deleted&#x60; field is not &#x60;true&#x60;). - For creates, the object ID must start with &#x60;#&#x60;. The provided ID is replaced with a server-generated ID. */
    public let object: CatalogObject

    public init(idempotencyKey: String, object: CatalogObject) {
        self.idempotencyKey = idempotencyKey
        self.object = object
    }

    public enum CodingKeys: String, CodingKey { 
        case idempotencyKey = "idempotency_key"
        case object
    }

}

