/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1BankAccount */

public struct V1BankAccount: Codable, Identifiable {

    /** The bank account&#39;s Square-issued ID. */
    public let id: String?
    /** The Square-issued ID of the merchant associated with the bank account. */
    public let merchantId: String?
    /** The name of the bank that manages the account. */
    public let bankName: String?
    /** The name associated with the bank account. */
    public let name: String?
    /** The bank account&#39;s routing number. */
    public let routingNumber: String?
    /** The last few digits of the bank account number. */
    public let accountNumberSuffix: String?
    /** The currency code of the currency associated with the bank account, in ISO 4217 format. For example, the currency code for US dollars is USD. */
    public let currencyCode: String?
    /** The bank account&#39;s type (for example, savings or checking). See [V1BankAccountType](#type-v1bankaccounttype) for possible values */
    public let type: V1BankAccountType?

    public init(id: String?, merchantId: String?, bankName: String?, name: String?, routingNumber: String?, accountNumberSuffix: String?, currencyCode: String?, type: V1BankAccountType?) {
        self.id = id
        self.merchantId = merchantId
        self.bankName = bankName
        self.name = name
        self.routingNumber = routingNumber
        self.accountNumberSuffix = accountNumberSuffix
        self.currencyCode = currencyCode
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case merchantId = "merchant_id"
        case bankName = "bank_name"
        case name
        case routingNumber = "routing_number"
        case accountNumberSuffix = "account_number_suffix"
        case currencyCode = "currency_code"
        case type
    }

}

