/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1Category */

public struct V1Category: Codable, Identifiable {

    /** The category&#39;s unique ID. */
    public let id: String?
    /** The category&#39;s name. */
    public let name: String?
    /** The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID. */
    public let v2Id: String?

    public init(id: String?, name: String?, v2Id: String?) {
        self.id = id
        self.name = name
        self.v2Id = v2Id
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case v2Id = "v2_id"
    }

}

