/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1CashDrawerEvent */

public struct V1CashDrawerEvent: Codable, Identifiable {

    /** The event&#39;s unique ID. */
    public let id: String?
    /** The ID of the employee that created the event. */
    public let employeeId: String?
    /** The type of event that occurred. See [V1CashDrawerEventEventType](#type-v1cashdrawereventeventtype) for possible values */
    public let eventType: V1CashDrawerEventEventType?
    /** The amount of money that was added to or removed from the cash drawer because of the event. This value can be positive (for added money) or negative (for removed money). */
    public let eventMoney: V1Money?
    /** The time when the event occurred, in ISO 8601 format. */
    public let createdAt: String?
    /** An optional description of the event, entered by the employee that created it. */
    public let _description: String?

    public init(id: String?, employeeId: String?, eventType: V1CashDrawerEventEventType?, eventMoney: V1Money?, createdAt: String?, _description: String?) {
        self.id = id
        self.employeeId = employeeId
        self.eventType = eventType
        self.eventMoney = eventMoney
        self.createdAt = createdAt
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case employeeId = "employee_id"
        case eventType = "event_type"
        case eventMoney = "event_money"
        case createdAt = "created_at"
        case _description = "description"
    }

}

