/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1CreateEmployeeRoleRequest: Codable {

    /** An EmployeeRole object with a name and permissions, and an optional owner flag. */
    public let employeeRole: V1EmployeeRole?

    public init(employeeRole: V1EmployeeRole?) {
        self.employeeRole = employeeRole
    }

    public enum CodingKeys: String, CodingKey { 
        case employeeRole = "employee_role"
    }

}

