/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1DeletePageCellRequest: Codable {

    /** The row of the cell to clear. Always an integer between 0 and 4, inclusive. Row 0 is the top row. */
    public let row: String?
    /** The column of the cell to clear. Always an integer between 0 and 4, inclusive. Column 0 is the leftmost column. */
    public let column: String?

    public init(row: String?, column: String?) {
        self.row = row
        self.column = column
    }

}

