/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1Discount */

public struct V1Discount: Codable, Identifiable {

    /** The discount&#39;s unique ID. */
    public let id: String?
    /** The discount&#39;s name. */
    public let name: String?
    /** The rate of the discount, as a string representation of a decimal number. A value of 0.07 corresponds to a rate of 7%. This rate is 0 if discount_type is VARIABLE_PERCENTAGE. */
    public let rate: String?
    /** The amount of the discount. This amount is 0 if discount_type is VARIABLE_AMOUNT. This field is not included for rate-based discounts. */
    public let amountMoney: V1Money?
    /** Indicates whether the discount is a FIXED value or entered at the time of sale. See [V1DiscountDiscountType](#type-v1discountdiscounttype) for possible values */
    public let discountType: V1DiscountDiscountType?
    /** Indicates whether a mobile staff member needs to enter their PIN to apply the discount to a payment. */
    public let pinRequired: Bool?
    /** The color of the discount&#39;s display label in Square Register, if not the default color. The default color is 9da2a6. See [V1DiscountColor](#type-v1discountcolor) for possible values */
    public let color: V1DiscountColor?
    /** The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID. */
    public let v2Id: String?

    public init(id: String?, name: String?, rate: String?, amountMoney: V1Money?, discountType: V1DiscountDiscountType?, pinRequired: Bool?, color: V1DiscountColor?, v2Id: String?) {
        self.id = id
        self.name = name
        self.rate = rate
        self.amountMoney = amountMoney
        self.discountType = discountType
        self.pinRequired = pinRequired
        self.color = color
        self.v2Id = v2Id
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case rate
        case amountMoney = "amount_money"
        case discountType = "discount_type"
        case pinRequired = "pin_required"
        case color
        case v2Id = "v2_id"
    }

}

