/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */
public enum V1FeeType: String, Codable {
    case caGst = "CA_GST"
    case caHst = "CA_HST"
    case caPst = "CA_PST"
    case caQst = "CA_QST"
    case jpConsumptionTax = "JP_CONSUMPTION_TAX"
    case caPeiPst = "CA_PEI_PST"
    case usSalesTax = "US_SALES_TAX"
    case other = "OTHER"

}
