/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1Item */

public struct V1Item: Codable, Identifiable {

    /** The item&#39;s ID. Must be unique among all entity IDs ever provided on behalf of the merchant. You can never reuse an ID. This value can include alphanumeric characters, dashes (-), and underscores (_). */
    public let id: String?
    /** The item&#39;s name. */
    public let name: String?
    /** The item&#39;s description. */
    public let _description: String?
    /** The item&#39;s type. This value is NORMAL for almost all items. See [V1ItemType](#type-v1itemtype) for possible values */
    public let type: V1ItemType?
    /** The color of the discount&#39;s display label in Square Register, if not the default color. The default color is 9da2a6. See [V1ItemColor](#type-v1itemcolor) for possible values */
    public let color: V1ItemColor?
    /** The text of the item&#39;s display label in Square Register. Only up to the first five characters of the string are used. */
    public let abbreviation: String?
    /** Indicates whether the item is viewable from the merchant&#39;s online store (PUBLIC) or PRIVATE. See [V1ItemVisibility](#type-v1itemvisibility) for possible values */
    public let visibility: V1ItemVisibility?
    /** If true, the item can be added to shipping orders from the merchant&#39;s online store. */
    public let availableOnline: Bool?
    /** The item&#39;s master image, if any. */
    public let masterImage: V1ItemImage?
    /** The category the item belongs to, if any. */
    public let category: V1Category?
    /** The item&#39;s variations. You must specify at least one variation. */
    public let variations: [V1Variation]?
    /** The modifier lists that apply to the item, if any. */
    public let modifierLists: [V1ModifierList]?
    /** The fees that apply to the item, if any. */
    public let fees: [V1Fee]?
    /** Deprecated. This field is not used. */
    public let taxable: Bool?
    /** The ID of the item&#39;s category, if any. */
    public let categoryId: String?
    /** If true, the item can be added to pickup orders from the merchant&#39;s online store. Default value: false */
    public let availableForPickup: Bool?
    /** The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID. */
    public let v2Id: String?

    public init(id: String?, name: String?, _description: String?, type: V1ItemType?, color: V1ItemColor?, abbreviation: String?, visibility: V1ItemVisibility?, availableOnline: Bool?, masterImage: V1ItemImage?, category: V1Category?, variations: [V1Variation]?, modifierLists: [V1ModifierList]?, fees: [V1Fee]?, taxable: Bool?, categoryId: String?, availableForPickup: Bool?, v2Id: String?) {
        self.id = id
        self.name = name
        self._description = _description
        self.type = type
        self.color = color
        self.abbreviation = abbreviation
        self.visibility = visibility
        self.availableOnline = availableOnline
        self.masterImage = masterImage
        self.category = category
        self.variations = variations
        self.modifierLists = modifierLists
        self.fees = fees
        self.taxable = taxable
        self.categoryId = categoryId
        self.availableForPickup = availableForPickup
        self.v2Id = v2Id
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case _description = "description"
        case type
        case color
        case abbreviation
        case visibility
        case availableOnline = "available_online"
        case masterImage = "master_image"
        case category
        case variations
        case modifierLists = "modifier_lists"
        case fees
        case taxable
        case categoryId = "category_id"
        case availableForPickup = "available_for_pickup"
        case v2Id = "v2_id"
    }

}

