/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1ItemImage */

public struct V1ItemImage: Codable, Identifiable {

    /** The image&#39;s unique ID. */
    public let id: String?
    /** The image&#39;s publicly accessible URL. */
    public let url: URL?

    public init(id: String?, url: URL?) {
        self.id = id
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case url
    }

}

