/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1ListTimecardsRequest: Codable {

    /** The order in which timecards are listed in the response, based on their created_at field. See [SortOrder](#type-sortorder) for possible values */
    public let order: SortOrder?
    /** If provided, the endpoint returns only timecards for the employee with the specified ID. */
    public let employeeId: String?
    /** If filtering results by their clockin_time field, the beginning of the requested reporting period, in ISO 8601 format. */
    public let beginClockinTime: String?
    /** If filtering results by their clockin_time field, the end of the requested reporting period, in ISO 8601 format. */
    public let endClockinTime: String?
    /** If filtering results by their clockout_time field, the beginning of the requested reporting period, in ISO 8601 format. */
    public let beginClockoutTime: String?
    /** If filtering results by their clockout_time field, the end of the requested reporting period, in ISO 8601 format. */
    public let endClockoutTime: String?
    /** If filtering results by their updated_at field, the beginning of the requested reporting period, in ISO 8601 format. */
    public let beginUpdatedAt: String?
    /** If filtering results by their updated_at field, the end of the requested reporting period, in ISO 8601 format. */
    public let endUpdatedAt: String?
    /** If true, only deleted timecards are returned. If false, only valid timecards are returned.If you don&#39;t provide this parameter, both valid and deleted timecards are returned. */
    public let deleted: Bool?
    /** The maximum integer number of employee entities to return in a single response. Default 100, maximum 200. */
    public let limit: Int?
    /** A pagination cursor to retrieve the next set of results for your original query to the endpoint. */
    public let batchToken: String?

    public init(order: SortOrder?, employeeId: String?, beginClockinTime: String?, endClockinTime: String?, beginClockoutTime: String?, endClockoutTime: String?, beginUpdatedAt: String?, endUpdatedAt: String?, deleted: Bool?, limit: Int?, batchToken: String?) {
        self.order = order
        self.employeeId = employeeId
        self.beginClockinTime = beginClockinTime
        self.endClockinTime = endClockinTime
        self.beginClockoutTime = beginClockoutTime
        self.endClockoutTime = endClockoutTime
        self.beginUpdatedAt = beginUpdatedAt
        self.endUpdatedAt = endUpdatedAt
        self.deleted = deleted
        self.limit = limit
        self.batchToken = batchToken
    }

    public enum CodingKeys: String, CodingKey { 
        case order
        case employeeId = "employee_id"
        case beginClockinTime = "begin_clockin_time"
        case endClockinTime = "end_clockin_time"
        case beginClockoutTime = "begin_clockout_time"
        case endClockoutTime = "end_clockout_time"
        case beginUpdatedAt = "begin_updated_at"
        case endUpdatedAt = "end_updated_at"
        case deleted
        case limit
        case batchToken = "batch_token"
    }

}

