/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1ListPaymentsRequest: Codable {

    /** The order in which payments are listed in the response. See [SortOrder](#type-sortorder) for possible values */
    public let order: SortOrder?
    /** The beginning of the requested reporting period, in ISO 8601 format. If this value is before January 1, 2013 (2013-01-01T00:00:00Z), this endpoint returns an error. Default value: The current time minus one year. */
    public let beginTime: String?
    /** The end of the requested reporting period, in ISO 8601 format. If this value is more than one year greater than begin_time, this endpoint returns an error. Default value: The current time. */
    public let endTime: String?
    /** The maximum number of payments to return in a single response. This value cannot exceed 200. */
    public let limit: Int?
    /** A pagination cursor to retrieve the next set of results for your original query to the endpoint. */
    public let batchToken: String?
    /** Indicates whether or not to include partial payments in the response. Partial payments will have the tenders collected so far, but the itemizations will be empty until the payment is completed. */
    public let includePartial: Bool?

    public init(order: SortOrder?, beginTime: String?, endTime: String?, limit: Int?, batchToken: String?, includePartial: Bool?) {
        self.order = order
        self.beginTime = beginTime
        self.endTime = endTime
        self.limit = limit
        self.batchToken = batchToken
        self.includePartial = includePartial
    }

    public enum CodingKeys: String, CodingKey { 
        case order
        case beginTime = "begin_time"
        case endTime = "end_time"
        case limit
        case batchToken = "batch_token"
        case includePartial = "include_partial"
    }

}

