/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1ListEmployeesRequest: Codable {

    /** The order in which employees are listed in the response, based on their created_at field.      Default value: ASC See [SortOrder](#type-sortorder) for possible values */
    public let order: SortOrder?
    /** If filtering results by their updated_at field, the beginning of the requested reporting period, in ISO 8601 format */
    public let beginUpdatedAt: String?
    /** If filtering results by there updated_at field, the end of the requested reporting period, in ISO 8601 format. */
    public let endUpdatedAt: String?
    /** If filtering results by their created_at field, the beginning of the requested reporting period, in ISO 8601 format. */
    public let beginCreatedAt: String?
    /** If filtering results by their created_at field, the end of the requested reporting period, in ISO 8601 format. */
    public let endCreatedAt: String?
    /** If provided, the endpoint returns only employee entities with the specified status (ACTIVE or INACTIVE). See [V1ListEmployeesRequestStatus](#type-v1listemployeesrequeststatus) for possible values */
    public let status: V1ListEmployeesRequestStatus?
    /** If provided, the endpoint returns only employee entities with the specified external_id. */
    public let externalId: String?
    /** The maximum integer number of employee entities to return in a single response. Default 100, maximum 200. */
    public let limit: Int?
    /** A pagination cursor to retrieve the next set of results for your original query to the endpoint. */
    public let batchToken: String?

    public init(order: SortOrder?, beginUpdatedAt: String?, endUpdatedAt: String?, beginCreatedAt: String?, endCreatedAt: String?, status: V1ListEmployeesRequestStatus?, externalId: String?, limit: Int?, batchToken: String?) {
        self.order = order
        self.beginUpdatedAt = beginUpdatedAt
        self.endUpdatedAt = endUpdatedAt
        self.beginCreatedAt = beginCreatedAt
        self.endCreatedAt = endCreatedAt
        self.status = status
        self.externalId = externalId
        self.limit = limit
        self.batchToken = batchToken
    }

    public enum CodingKeys: String, CodingKey { 
        case order
        case beginUpdatedAt = "begin_updated_at"
        case endUpdatedAt = "end_updated_at"
        case beginCreatedAt = "begin_created_at"
        case endCreatedAt = "end_created_at"
        case status
        case externalId = "external_id"
        case limit
        case batchToken = "batch_token"
    }

}

