/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1ListItemsRequest: Codable {

    /** A pagination cursor to retrieve the next set of results for your original query to the endpoint. */
    public let batchToken: String?

    public init(batchToken: String?) {
        self.batchToken = batchToken
    }

    public enum CodingKeys: String, CodingKey { 
        case batchToken = "batch_token"
    }

}

