/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Additional information for a single-location account specified by its associated business account, if it has one. */

public struct V1MerchantLocationDetails: Codable {

    /** The nickname assigned to the single-location account by the parent business. This value appears in the parent business&#39;s multi-location dashboard. */
    public let nickname: String?

    public init(nickname: String?) {
        self.nickname = nickname
    }

}

