/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */
public enum V1MerchantBusinessType: String, Codable {
    case accounting = "ACCOUNTING"
    case apparelAndAccessoryShops = "APPAREL_AND_ACCESSORY_SHOPS"
    case artDealersGalleries = "ART_DEALERS_GALLERIES"
    case artDesignAndPhotography = "ART_DESIGN_AND_PHOTOGRAPHY"
    case barClubLounge = "BAR_CLUB_LOUNGE"
    case beautyAndBarberShops = "BEAUTY_AND_BARBER_SHOPS"
    case bookStores = "BOOK_STORES"
    case businessServices = "BUSINESS_SERVICES"
    case catering = "CATERING"
    case charitableSocialServiceOrganizations = "CHARITABLE_SOCIAL_SERVICE_ORGANIZATIONS"
    case charitibleOrgs = "CHARITIBLE_ORGS"
    case cleaningServices = "CLEANING_SERVICES"
    case computerEquipmentSoftwareMaintenanceRepairServices = "COMPUTER_EQUIPMENT_SOFTWARE_MAINTENANCE_REPAIR_SERVICES"
    case consultant = "CONSULTANT"
    case contractors = "CONTRACTORS"
    case deliveryServices = "DELIVERY_SERVICES"
    case dentistry = "DENTISTRY"
    case education = "EDUCATION"
    case foodStoresConvenienceStoresAndSpecialtyMarkets = "FOOD_STORES_CONVENIENCE_STORES_AND_SPECIALTY_MARKETS"
    case foodTruckCart = "FOOD_TRUCK_CART"
    case furnitureHomeAndOfficeEquipment = "FURNITURE_HOME_AND_OFFICE_EQUIPMENT"
    case furnitureHomeGoods = "FURNITURE_HOME_GOODS"
    case hotelsAndLodging = "HOTELS_AND_LODGING"
    case individualUse = "INDIVIDUAL_USE"
    case jewelryAndWatches = "JEWELRY_AND_WATCHES"
    case landscapingAndHorticulturalServices = "LANDSCAPING_AND_HORTICULTURAL_SERVICES"
    case languageSchools = "LANGUAGE_SCHOOLS"
    case legalServices = "LEGAL_SERVICES"
    case medicalPractitioners = "MEDICAL_PRACTITIONERS"
    case medicalServicesAndHealthPractitioners = "MEDICAL_SERVICES_AND_HEALTH_PRACTITIONERS"
    case membershipOrganizations = "MEMBERSHIP_ORGANIZATIONS"
    case musicAndEntertainment = "MUSIC_AND_ENTERTAINMENT"
    case other = "OTHER"
    case outdoorMarkets = "OUTDOOR_MARKETS"
    case personalServices = "PERSONAL_SERVICES"
    case politicalOrganizations = "POLITICAL_ORGANIZATIONS"
    case professionalServices = "PROFESSIONAL_SERVICES"
    case realEstate = "REAL_ESTATE"
    case recreationServices = "RECREATION_SERVICES"
    case repairShopsAndRelatedServices = "REPAIR_SHOPS_AND_RELATED_SERVICES"
    case restaurants = "RESTAURANTS"
    case retailShops = "RETAIL_SHOPS"
    case schoolsAndEducationalServices = "SCHOOLS_AND_EDUCATIONAL_SERVICES"
    case sportingGoods = "SPORTING_GOODS"
    case taxicabsAndLimousines = "TAXICABS_AND_LIMOUSINES"
    case ticketSales = "TICKET_SALES"
    case tourism = "TOURISM"
    case travelTourism = "TRAVEL_TOURISM"
    case veterinaryServices = "VETERINARY_SERVICES"
    case webDevDesign = "WEB_DEV_DESIGN"

}
