/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1ModifierList */

public struct V1ModifierList: Codable, Identifiable {

    /** The modifier list&#39;s unique ID. */
    public let id: String?
    /** The modifier list&#39;s name. */
    public let name: String?
    /** Indicates whether MULTIPLE options or a SINGLE option from the modifier list can be applied to a single item. See [V1ModifierListSelectionType](#type-v1modifierlistselectiontype) for possible values */
    public let selectionType: V1ModifierListSelectionType?
    /** The options included in the modifier list. */
    public let modifierOptions: [V1ModifierOption]?
    /** The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID. */
    public let v2Id: String?

    public init(id: String?, name: String?, selectionType: V1ModifierListSelectionType?, modifierOptions: [V1ModifierOption]?, v2Id: String?) {
        self.id = id
        self.name = name
        self.selectionType = selectionType
        self.modifierOptions = modifierOptions
        self.v2Id = v2Id
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case selectionType = "selection_type"
        case modifierOptions = "modifier_options"
        case v2Id = "v2_id"
    }

}

