/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1ModifierOption */

public struct V1ModifierOption: Codable, Identifiable {

    /** The modifier option&#39;s unique ID. */
    public let id: String?
    /** The modifier option&#39;s name. */
    public let name: String?
    /** The modifier option&#39;s price. */
    public let priceMoney: V1Money?
    /** If true, the modifier option is the default option in a modifier list for which selection_type is SINGLE. */
    public let onByDefault: Bool?
    /** Indicates the modifier option&#39;s list position when displayed in Square Register and the merchant dashboard. If more than one modifier option in the same modifier list has the same ordinal value, those options are displayed in alphabetical order. */
    public let ordinal: Int?
    /** The ID of the modifier list the option belongs to. */
    public let modifierListId: String?
    /** The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID. */
    public let v2Id: String?

    public init(id: String?, name: String?, priceMoney: V1Money?, onByDefault: Bool?, ordinal: Int?, modifierListId: String?, v2Id: String?) {
        self.id = id
        self.name = name
        self.priceMoney = priceMoney
        self.onByDefault = onByDefault
        self.ordinal = ordinal
        self.modifierListId = modifierListId
        self.v2Id = v2Id
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case priceMoney = "price_money"
        case onByDefault = "on_by_default"
        case ordinal
        case modifierListId = "modifier_list_id"
        case v2Id = "v2_id"
    }

}

