/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1Page */

public struct V1Page: Codable, Identifiable {

    /** The page&#39;s unique identifier. */
    public let id: String?
    /** The page&#39;s name, if any. */
    public let name: String?
    /** The page&#39;s position in the merchant&#39;s list of pages. Always an integer between 0 and 6, inclusive. */
    public let pageIndex: Int?
    /** The cells included on the page. */
    public let cells: [V1PageCell]?

    public init(id: String?, name: String?, pageIndex: Int?, cells: [V1PageCell]?) {
        self.id = id
        self.name = name
        self.pageIndex = pageIndex
        self.cells = cells
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case pageIndex = "page_index"
        case cells
    }

}

