/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1PaymentTax */

public struct V1PaymentTax: Codable {

    /** Any errors that occurred during the request. */
    public let errors: [ModelError]?
    /** The merchant-defined name of the tax. */
    public let name: String?
    /** The amount of money that this tax adds to the payment. */
    public let appliedMoney: V1Money?
    /** The rate of the tax, as a string representation of a decimal number. A value of 0.07 corresponds to a rate of 7%. */
    public let rate: String?
    /** Whether the tax is an ADDITIVE tax or an INCLUSIVE tax. See [V1PaymentTaxInclusionType](#type-v1paymenttaxinclusiontype) for possible values */
    public let inclusionType: V1PaymentTaxInclusionType?
    /** The ID of the tax, if available. Taxes applied in older versions of Square Register might not have an ID. */
    public let feeId: String?

    public init(errors: [ModelError]?, name: String?, appliedMoney: V1Money?, rate: String?, inclusionType: V1PaymentTaxInclusionType?, feeId: String?) {
        self.errors = errors
        self.name = name
        self.appliedMoney = appliedMoney
        self.rate = rate
        self.inclusionType = inclusionType
        self.feeId = feeId
    }

    public enum CodingKeys: String, CodingKey { 
        case errors
        case name
        case appliedMoney = "applied_money"
        case rate
        case inclusionType = "inclusion_type"
        case feeId = "fee_id"
    }

}

