/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1PaymentItemDetail */

public struct V1PaymentItemDetail: Codable {

    /** The name of the item&#39;s merchant-defined category, if any. */
    public let categoryName: String?
    /**  The item&#39;s merchant-defined SKU, if any. */
    public let sku: String?
    /** The unique ID of the item purchased, if any. */
    public let itemId: String?
    /** The unique ID of the item variation purchased, if any. */
    public let itemVariationId: String?

    public init(categoryName: String?, sku: String?, itemId: String?, itemVariationId: String?) {
        self.categoryName = categoryName
        self.sku = sku
        self.itemId = itemId
        self.itemVariationId = itemVariationId
    }

    public enum CodingKeys: String, CodingKey { 
        case categoryName = "category_name"
        case sku
        case itemId = "item_id"
        case itemVariationId = "item_variation_id"
    }

}

