/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1PaymentSurcharge */

public struct V1PaymentSurcharge: Codable {

    /** The name of the surcharge. */
    public let name: String?
    /** The amount of money applied to the order as a result of the surcharge. */
    public let appliedMoney: V1Money?
    /** The amount of the surcharge as a percentage. The percentage is provided as a string representing the decimal equivalent of the percentage. For example, \&quot;0.7\&quot; corresponds to a 7% surcharge. Exactly one of rate or amount_money should be set. */
    public let rate: String?
    /** The amount of the surcharge as a Money object. Exactly one of rate or amount_money should be set. */
    public let amountMoney: V1Money?
    /** Indicates the source of the surcharge. For example, if it was applied as an automatic gratuity for a large group. See [V1PaymentSurchargeType](#type-v1paymentsurchargetype) for possible values */
    public let type: V1PaymentSurchargeType?
    /** Indicates whether the surcharge is taxable. */
    public let taxable: Bool?
    /** The list of taxes that should be applied to the surcharge. */
    public let taxes: [V1PaymentTax]?
    /** A Square-issued unique identifier associated with the surcharge. */
    public let surchargeId: String?

    public init(name: String?, appliedMoney: V1Money?, rate: String?, amountMoney: V1Money?, type: V1PaymentSurchargeType?, taxable: Bool?, taxes: [V1PaymentTax]?, surchargeId: String?) {
        self.name = name
        self.appliedMoney = appliedMoney
        self.rate = rate
        self.amountMoney = amountMoney
        self.type = type
        self.taxable = taxable
        self.taxes = taxes
        self.surchargeId = surchargeId
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case appliedMoney = "applied_money"
        case rate
        case amountMoney = "amount_money"
        case type
        case taxable
        case taxes
        case surchargeId = "surcharge_id"
    }

}

