/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** Represents a phone number. */

public struct V1PhoneNumber: Codable {

    /** The phone number&#39;s international calling code. For US phone numbers, this value is +1. */
    public let callingCode: String
    /** The phone number. */
    public let number: String

    public init(callingCode: String, number: String) {
        self.callingCode = callingCode
        self.number = number
    }

    public enum CodingKeys: String, CodingKey { 
        case callingCode = "calling_code"
        case number
    }

}

