/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1SettlementEntry */

public struct V1SettlementEntry: Codable {

    /** The settlement&#39;s unique identifier. */
    public let paymentId: String?
    /** The settlement&#39;s current status. See [V1SettlementEntryType](#type-v1settlemententrytype) for possible values */
    public let type: V1SettlementEntryType?
    /** The total amount of money this entry contributes to the total settlement amount. */
    public let amountMoney: V1Money?
    /** The amount of all Square fees associated with this settlement entry. This value is always negative or zero. */
    public let feeMoney: V1Money?

    public init(paymentId: String?, type: V1SettlementEntryType?, amountMoney: V1Money?, feeMoney: V1Money?) {
        self.paymentId = paymentId
        self.type = type
        self.amountMoney = amountMoney
        self.feeMoney = feeMoney
    }

    public enum CodingKeys: String, CodingKey { 
        case paymentId = "payment_id"
        case type
        case amountMoney = "amount_money"
        case feeMoney = "fee_money"
    }

}

