/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1Settlement */

public struct V1Settlement: Codable, Identifiable {

    /** The settlement&#39;s unique identifier. */
    public let id: String?
    /** The settlement&#39;s current status. See [V1SettlementStatus](#type-v1settlementstatus) for possible values */
    public let status: V1SettlementStatus?
    /** The amount of money involved in the settlement. A positive amount indicates a deposit, and a negative amount indicates a withdrawal. This amount is never zero. */
    public let totalMoney: V1Money?
    /** The time when the settlement was submitted for deposit or withdrawal, in ISO 8601 format. */
    public let initiatedAt: String?
    /** The Square-issued unique identifier for the bank account associated with the settlement. */
    public let bankAccountId: String?
    /** The entries included in this settlement. */
    public let entries: [V1SettlementEntry]?

    public init(id: String?, status: V1SettlementStatus?, totalMoney: V1Money?, initiatedAt: String?, bankAccountId: String?, entries: [V1SettlementEntry]?) {
        self.id = id
        self.status = status
        self.totalMoney = totalMoney
        self.initiatedAt = initiatedAt
        self.bankAccountId = bankAccountId
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case status
        case totalMoney = "total_money"
        case initiatedAt = "initiated_at"
        case bankAccountId = "bank_account_id"
        case entries
    }

}

