/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */
public enum V1TenderEntryMethod: String, Codable {
    case manual = "MANUAL"
    case scanned = "SCANNED"
    case squareCash = "SQUARE_CASH"
    case squareWallet = "SQUARE_WALLET"
    case swiped = "SWIPED"
    case webForm = "WEB_FORM"
    case other = "OTHER"

}
