/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/**  */

public struct V1UpdatePageCellRequest: Codable {

    /** An object containing the fields to POST for the request.  See the corresponding object definition for field details. */
    public let body: V1PageCell

    public init(body: V1PageCell) {
        self.body = body
    }

}

