/**
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11-SNAPSHOT
 *
 */


import Foundation


/** V1UpdateOrderRequest */

public struct V1UpdateOrderRequest: Codable {

    /** The action to perform on the order (COMPLETE, CANCEL, or REFUND). See [V1UpdateOrderRequestAction](#type-v1updateorderrequestaction) for possible values */
    public let action: V1UpdateOrderRequestAction
    /** The tracking number of the shipment associated with the order. Only valid if action is COMPLETE. */
    public let shippedTrackingNumber: String?
    /** A merchant-specified note about the completion of the order. Only valid if action is COMPLETE. */
    public let completedNote: String?
    /** A merchant-specified note about the refunding of the order. Only valid if action is REFUND. */
    public let refundedNote: String?
    /** A merchant-specified note about the canceling of the order. Only valid if action is CANCEL. */
    public let canceledNote: String?

    public init(action: V1UpdateOrderRequestAction, shippedTrackingNumber: String?, completedNote: String?, refundedNote: String?, canceledNote: String?) {
        self.action = action
        self.shippedTrackingNumber = shippedTrackingNumber
        self.completedNote = completedNote
        self.refundedNote = refundedNote
        self.canceledNote = canceledNote
    }

    public enum CodingKeys: String, CodingKey { 
        case action
        case shippedTrackingNumber = "shipped_tracking_number"
        case completedNote = "completed_note"
        case refundedNote = "refunded_note"
        case canceledNote = "canceled_note"
    }

}

